# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'gui/rn_admin_validation_ui.ui'
#
# Created: Wed Oct 28 16:06:34 2015
#      by: PyQt4 UI code generator 4.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_validationDialog(object):
    def setupUi(self, validationDialog):
        validationDialog.setObjectName(_fromUtf8("validationDialog"))
        validationDialog.setWindowModality(QtCore.Qt.ApplicationModal)
        validationDialog.resize(308, 611)
        validationDialog.setModal(True)
        validationDialog.setWindowFlags(QtCore.Qt.CustomizeWindowHint | QtCore.Qt.WindowTitleHint)
        self.gridLayout_3 = QtGui.QGridLayout(validationDialog)
        self.gridLayout_3.setObjectName(_fromUtf8("gridLayout_3"))
        self.okCancelButtons = QtGui.QDialogButtonBox(validationDialog)
        self.okCancelButtons.setStandardButtons(QtGui.QDialogButtonBox.Cancel|QtGui.QDialogButtonBox.Ok)
        self.okCancelButtons.setObjectName(_fromUtf8("okCancelButtons"))
        self.gridLayout_3.addWidget(self.okCancelButtons, 7, 0, 1, 1)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.reportLabel = QtGui.QLabel(validationDialog)
        self.reportLabel.setObjectName(_fromUtf8("reportLabel"))
        self.horizontalLayout.addWidget(self.reportLabel)
        self.screenRadioButton = QtGui.QRadioButton(validationDialog)
        self.screenRadioButton.setObjectName(_fromUtf8("screenRadioButton"))
        self.horizontalLayout.addWidget(self.screenRadioButton)
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.fileRadioButton = QtGui.QRadioButton(validationDialog)
        self.fileRadioButton.setObjectName(_fromUtf8("fileRadioButton"))
        self.horizontalLayout.addWidget(self.fileRadioButton)
        spacerItem1 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.gridLayout_3.addLayout(self.horizontalLayout, 0, 0, 1, 1)
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.filePathLineEdit = QtGui.QLineEdit(validationDialog)
        self.filePathLineEdit.setStyleSheet(_fromUtf8(""))
        self.filePathLineEdit.setText(_fromUtf8(""))
        self.filePathLineEdit.setReadOnly(False)
        self.filePathLineEdit.setObjectName(_fromUtf8("filePathLineEdit"))
        self.horizontalLayout_2.addWidget(self.filePathLineEdit)
        self.openPushButton = QtGui.QPushButton(validationDialog)
        self.openPushButton.setText(_fromUtf8(""))
        self.openPushButton.setObjectName(_fromUtf8("openPushButton"))
        self.horizontalLayout_2.addWidget(self.openPushButton)
        self.gridLayout_3.addLayout(self.horizontalLayout_2, 1, 0, 1, 1)
        self.horizontalLayout_4 = QtGui.QHBoxLayout()
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        self.selectAllButton = QtGui.QPushButton(validationDialog)
        self.selectAllButton.setObjectName(_fromUtf8("selectAllButton"))
        self.horizontalLayout_4.addWidget(self.selectAllButton)
        self.clearAllButton = QtGui.QPushButton(validationDialog)
        self.clearAllButton.setObjectName(_fromUtf8("clearAllButton"))
        self.horizontalLayout_4.addWidget(self.clearAllButton)
        spacerItem2 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem2)
        self.gridLayout_3.addLayout(self.horizontalLayout_4, 6, 0, 1, 1)

        self.streetOptGroupBox = QtGui.QGroupBox(validationDialog)
        self.streetOptGroupBox.setObjectName(_fromUtf8("streetOptGroupBox"))
        self.gridLayout_2 = QtGui.QGridLayout(self.streetOptGroupBox)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.gridLayout = QtGui.QGridLayout()
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.dupStreetCheckBox = QtGui.QCheckBox(self.streetOptGroupBox)
        self.dupStreetCheckBox.setObjectName(_fromUtf8("dupStreetCheckBox"))
        self.gridLayout.addWidget(self.dupStreetCheckBox, 0, 0, 1, 1)
        self.notStreetEsuCheckBox = QtGui.QCheckBox(self.streetOptGroupBox)
        self.notStreetEsuCheckBox.setObjectName(_fromUtf8("notStreetEsuCheckBox"))
        self.gridLayout.addWidget(self.notStreetEsuCheckBox, 1, 0, 1, 1)
        self.notType3CheckBox = QtGui.QCheckBox(self.streetOptGroupBox)
        self.notType3CheckBox.setObjectName(_fromUtf8("notType3CheckBox"))
        self.gridLayout.addWidget(self.notType3CheckBox, 2, 0, 1, 1)
        self.incFootPathCheckBox = QtGui.QCheckBox(self.streetOptGroupBox)
        self.incFootPathCheckBox.setObjectName(_fromUtf8("incFootPathCheckBox"))
        self.gridLayout.addWidget(self.incFootPathCheckBox, 2, 1, 1, 1)
        self.gridLayout_2.addLayout(self.gridLayout, 0, 0, 1, 1)
        self.gridLayout_3.addWidget(self.streetOptGroupBox, 2, 0, 1, 1)
        self.esuOptGroupBox = QtGui.QGroupBox(validationDialog)
        self.esuOptGroupBox.setObjectName(_fromUtf8("esuOptGroupBox"))
        self.gridLayout_5 = QtGui.QGridLayout(self.esuOptGroupBox)
        self.gridLayout_5.setObjectName(_fromUtf8("gridLayout_5"))
        self.gridLayout_4 = QtGui.QGridLayout()
        self.gridLayout_4.setObjectName(_fromUtf8("gridLayout_4"))
        self.dupEsuRefCheckBox = QtGui.QCheckBox(self.esuOptGroupBox)
        self.dupEsuRefCheckBox.setObjectName(_fromUtf8("dupEsuRefCheckBox"))
        self.gridLayout_4.addWidget(self.dupEsuRefCheckBox, 0, 0, 1, 1)
        self.notEsuStreetCheckBox = QtGui.QCheckBox(self.esuOptGroupBox)
        self.notEsuStreetCheckBox.setObjectName(_fromUtf8("notEsuStreetCheckBox"))
        self.gridLayout_4.addWidget(self.notEsuStreetCheckBox, 1, 0, 1, 1)
        self.invCrossRefCheckBox = QtGui.QCheckBox(self.esuOptGroupBox)
        self.invCrossRefCheckBox.setObjectName(_fromUtf8("invCrossRefCheckBox"))
        self.gridLayout_4.addWidget(self.invCrossRefCheckBox, 2, 0, 1, 1)
        self.startEndCheckBox = QtGui.QCheckBox(self.esuOptGroupBox)
        self.startEndCheckBox.setObjectName(_fromUtf8("startEndCheckBox"))
        self.gridLayout_4.addWidget(self.startEndCheckBox, 3, 0, 1, 1)
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.metresSpinBox = QtGui.QSpinBox(self.esuOptGroupBox)
        self.metresSpinBox.setButtonSymbols(QtGui.QAbstractSpinBox.NoButtons)
        self.metresSpinBox.setMaximum(999)
        self.metresSpinBox.setSingleStep(1)
        self.metresSpinBox.setObjectName(_fromUtf8("metresSpinBox"))
        self.horizontalLayout_3.addWidget(self.metresSpinBox)
        self.toleranceLabel = QtGui.QLabel(self.esuOptGroupBox)
        self.toleranceLabel.setObjectName(_fromUtf8("toleranceLabel"))
        self.horizontalLayout_3.addWidget(self.toleranceLabel)
        self.gridLayout_4.addLayout(self.horizontalLayout_3, 3, 1, 1, 1)
        self.tinyEsuCheckBox = QtGui.QCheckBox(self.esuOptGroupBox)
        self.tinyEsuCheckBox.setObjectName(_fromUtf8("tinyEsuCheckBox"))
        self.gridLayout_4.addWidget(self.tinyEsuCheckBox, 4, 0, 1, 1)
        self.gridLayout_5.addLayout(self.gridLayout_4, 0, 0, 1, 1)
        self.gridLayout_3.addWidget(self.esuOptGroupBox, 3, 0, 1, 1)
        self.asdOptGroupBox = QtGui.QGroupBox(validationDialog)
        self.asdOptGroupBox.setObjectName(_fromUtf8("asdOptGroupBox"))
        self.verticalLayout_3 = QtGui.QVBoxLayout(self.asdOptGroupBox)
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.verticalLayout_2 = QtGui.QVBoxLayout()
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.notMaintReinsCheckBox = QtGui.QCheckBox(self.asdOptGroupBox)
        self.notMaintReinsCheckBox.setObjectName(_fromUtf8("notMaintReinsCheckBox"))
        self.verticalLayout_2.addWidget(self.notMaintReinsCheckBox)
        self.asdStartEndCheckBox = QtGui.QCheckBox(self.asdOptGroupBox)
        self.asdStartEndCheckBox.setObjectName(_fromUtf8("asdStartEndCheckBox"))
        self.verticalLayout_2.addWidget(self.asdStartEndCheckBox)
        self.verticalLayout_3.addLayout(self.verticalLayout_2)
        self.gridLayout_3.addWidget(self.asdOptGroupBox, 4, 0, 1, 1)
        self.polyOptGroupBox = QtGui.QGroupBox(validationDialog)
        self.polyOptGroupBox.setObjectName(_fromUtf8("polyOptGroupBox"))
        self.verticalLayout_5 = QtGui.QVBoxLayout(self.polyOptGroupBox)
        self.verticalLayout_5.setObjectName(_fromUtf8("verticalLayout_5"))
        self.verticalLayout_4 = QtGui.QVBoxLayout()
        self.verticalLayout_4.setObjectName(_fromUtf8("verticalLayout_4"))
        self.notMaintPolysCheckBox = QtGui.QCheckBox(self.polyOptGroupBox)
        self.notMaintPolysCheckBox.setObjectName(_fromUtf8("notMaintPolysCheckBox"))
        self.verticalLayout_4.addWidget(self.notMaintPolysCheckBox)
        self.notPolysMaintCheckBox = QtGui.QCheckBox(self.polyOptGroupBox)
        self.notPolysMaintCheckBox.setObjectName(_fromUtf8("notPolysMaintCheckBox"))
        self.verticalLayout_4.addWidget(self.notPolysMaintCheckBox)
        self.tinyPolysCheckBox = QtGui.QCheckBox(self.polyOptGroupBox)
        self.tinyPolysCheckBox.setObjectName(_fromUtf8("tinyPolysCheckBox"))
        self.verticalLayout_4.addWidget(self.tinyPolysCheckBox)
        self.verticalLayout_5.addLayout(self.verticalLayout_4)
        self.gridLayout_3.addWidget(self.polyOptGroupBox, 5, 0, 1, 1)

        self.retranslateUi(validationDialog)
        QtCore.QMetaObject.connectSlotsByName(validationDialog)

    def retranslateUi(self, validationDialog):
        validationDialog.setWindowTitle(_translate("validationDialog", "Validation Report Options", None))
        self.reportLabel.setText(_translate("validationDialog", "Report Location:", None))
        self.screenRadioButton.setText(_translate("validationDialog", "Screen", None))
        self.fileRadioButton.setText(_translate("validationDialog", "File", None))
        self.selectAllButton.setText(_translate("validationDialog", "Select All", None))
        self.clearAllButton.setText(_translate("validationDialog", "Clear All", None))
        self.esuOptGroupBox.setTitle(_translate("validationDialog", "ESU Options", None))
        self.dupEsuRefCheckBox.setText(_translate("validationDialog", "Duplicate ESU References", None))
        self.notEsuStreetCheckBox.setText(_translate("validationDialog", "ESUs not linked to Street", None))
        self.invCrossRefCheckBox.setText(_translate("validationDialog", "Invalid Cross-references", None))
        self.startEndCheckBox.setText(_translate("validationDialog", "Start + End Co-ords (slow)", None))
        self.toleranceLabel.setText(_translate("validationDialog", "m Tolerance", None))
        self.tinyEsuCheckBox.setText(_translate("validationDialog", "Tiny ESUs", None))
        self.streetOptGroupBox.setTitle(_translate("validationDialog", "Street Options", None))
        self.dupStreetCheckBox.setText(_translate("validationDialog", "Duplicate Street Descriptions", None))
        self.notStreetEsuCheckBox.setText(_translate("validationDialog", "Streets not linked to ESU", None))
        self.notType3CheckBox.setText(_translate("validationDialog", "Streets without Type 3", None))
        self.incFootPathCheckBox.setText(_translate("validationDialog", "(inc. Foothpath)", None))
        self.asdOptGroupBox.setTitle(_translate("validationDialog", "ASD Options", None))
        self.notMaintReinsCheckBox.setText(_translate("validationDialog", "Streets without Maint / Reinstatement", None))
        self.asdStartEndCheckBox.setText(_translate("validationDialog", "ASD Start + End Co-ords", None))
        self.polyOptGroupBox.setTitle(_translate("validationDialog", "Polygon Options", None))
        self.notMaintPolysCheckBox.setText(_translate("validationDialog", "Maint records not linked to Polys", None))
        self.notPolysMaintCheckBox.setText(_translate("validationDialog", "Polys not linked to Maint Records", None))
        self.tinyPolysCheckBox.setText(_translate("validationDialog", "Tiny Polys", None))


if __name__ == "__main__":
    import sys
    app = QtGui.QApplication(sys.argv)
    validationDialog = QtGui.QDialog()
    ui = Ui_validationDialog()
    ui.setupUi(validationDialog)
    validationDialog.show()
    sys.exit(app.exec_())

