# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'rn_admin_validation_summary.ui'
#
# Created: Fri Feb 26 10:16:22 2016
#      by: PyQt4 UI code generator 4.10.2
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_validationSummaryDialog(object):
    def setupUi(self, validationSummaryDialog):
        validationSummaryDialog.setObjectName(_fromUtf8("validationSummaryDialog"))
        validationSummaryDialog.resize(1051, 810)
        validationSummaryDialog.setMinimumSize(QtCore.QSize(1051, 810))
        self.gridLayout_7 = QtGui.QGridLayout(validationSummaryDialog)
        self.gridLayout_7.setObjectName(_fromUtf8("gridLayout_7"))
        self.tabWidget = QtGui.QTabWidget(validationSummaryDialog)
        self.tabWidget.setObjectName(_fromUtf8("tabWidget"))
        self.streetOptTab = QtGui.QWidget()
        self.streetOptTab.setObjectName(_fromUtf8("streetOptTab"))
        self.gridLayout_25 = QtGui.QGridLayout(self.streetOptTab)
        self.gridLayout_25.setObjectName(_fromUtf8("gridLayout_25"))
        self.groupBox = QtGui.QGroupBox(self.streetOptTab)
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self.gridLayout_24 = QtGui.QGridLayout(self.groupBox)
        self.gridLayout_24.setObjectName(_fromUtf8("gridLayout_24"))
        self.dupDesTable = QtGui.QTableWidget(self.groupBox)
        self.dupDesTable.setMinimumSize(QtCore.QSize(494, 180))
        self.dupDesTable.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.dupDesTable.setAutoScroll(True)
        self.dupDesTable.setEditTriggers(QtGui.QAbstractItemView.NoEditTriggers)
        self.dupDesTable.setAlternatingRowColors(True)
        self.dupDesTable.setSelectionMode(QtGui.QAbstractItemView.ContiguousSelection)
        self.dupDesTable.setSelectionBehavior(QtGui.QAbstractItemView.SelectRows)
        self.dupDesTable.setObjectName(_fromUtf8("dupDesTable"))
        self.dupDesTable.setColumnCount(0)
        self.dupDesTable.setRowCount(0)
        self.gridLayout_24.addWidget(self.dupDesTable, 0, 0, 1, 1)
        self.gridLayout_25.addWidget(self.groupBox, 0, 0, 1, 1)
        self.groupBox_2 = QtGui.QGroupBox(self.streetOptTab)
        self.groupBox_2.setObjectName(_fromUtf8("groupBox_2"))
        self.gridLayout_23 = QtGui.QGridLayout(self.groupBox_2)
        self.gridLayout_23.setObjectName(_fromUtf8("gridLayout_23"))
        self.noLinkEsuTable = QtGui.QTableWidget(self.groupBox_2)
        self.noLinkEsuTable.setMinimumSize(QtCore.QSize(462, 180))
        self.noLinkEsuTable.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.noLinkEsuTable.setEditTriggers(QtGui.QAbstractItemView.NoEditTriggers)
        self.noLinkEsuTable.setAlternatingRowColors(True)
        self.noLinkEsuTable.setSelectionBehavior(QtGui.QAbstractItemView.SelectRows)
        self.noLinkEsuTable.setObjectName(_fromUtf8("noLinkEsuTable"))
        self.noLinkEsuTable.setColumnCount(0)
        self.noLinkEsuTable.setRowCount(0)
        self.gridLayout_23.addWidget(self.noLinkEsuTable, 0, 0, 1, 1)
        self.gridLayout_25.addWidget(self.groupBox_2, 1, 0, 1, 1)
        self.type3GroupBox = QtGui.QGroupBox(self.streetOptTab)
        self.type3GroupBox.setObjectName(_fromUtf8("type3GroupBox"))
        self.gridLayout = QtGui.QGridLayout(self.type3GroupBox)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.noType3Table = QtGui.QTableWidget(self.type3GroupBox)
        self.noType3Table.setMinimumSize(QtCore.QSize(332, 180))
        self.noType3Table.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.noType3Table.setEditTriggers(QtGui.QAbstractItemView.NoEditTriggers)
        self.noType3Table.setAlternatingRowColors(True)
        self.noType3Table.setSelectionBehavior(QtGui.QAbstractItemView.SelectRows)
        self.noType3Table.setObjectName(_fromUtf8("noType3Table"))
        self.noType3Table.setColumnCount(0)
        self.noType3Table.setRowCount(0)
        self.gridLayout.addWidget(self.noType3Table, 0, 0, 1, 1)
        self.noType3Label = QtGui.QLabel(self.type3GroupBox)
        self.noType3Label.setText(_fromUtf8(""))
        self.noType3Label.setObjectName(_fromUtf8("noType3Label"))
        self.gridLayout.addWidget(self.noType3Label, 1, 0, 1, 1)
        self.gridLayout_25.addWidget(self.type3GroupBox, 2, 0, 1, 1)
        self.tabWidget.addTab(self.streetOptTab, _fromUtf8(""))
        self.esuOptTab = QtGui.QWidget()
        self.esuOptTab.setObjectName(_fromUtf8("esuOptTab"))
        self.gridLayout_5 = QtGui.QGridLayout(self.esuOptTab)
        self.gridLayout_5.setObjectName(_fromUtf8("gridLayout_5"))
        self.horizontalLayout_5 = QtGui.QHBoxLayout()
        self.horizontalLayout_5.setObjectName(_fromUtf8("horizontalLayout_5"))
        self.dupEsuRefGroupBox = QtGui.QGroupBox(self.esuOptTab)
        self.dupEsuRefGroupBox.setObjectName(_fromUtf8("dupEsuRefGroupBox"))
        self.gridLayout_3 = QtGui.QGridLayout(self.dupEsuRefGroupBox)
        self.gridLayout_3.setObjectName(_fromUtf8("gridLayout_3"))
        self.dupEsuRefTable = QtGui.QTableWidget(self.dupEsuRefGroupBox)
        self.dupEsuRefTable.setEditTriggers(QtGui.QAbstractItemView.NoEditTriggers)
        self.dupEsuRefTable.setAlternatingRowColors(True)
        self.dupEsuRefTable.setSelectionMode(QtGui.QAbstractItemView.ContiguousSelection)
        self.dupEsuRefTable.setSelectionBehavior(QtGui.QAbstractItemView.SelectRows)
        self.dupEsuRefTable.setObjectName(_fromUtf8("dupEsuRefTable"))
        self.dupEsuRefTable.setColumnCount(0)
        self.dupEsuRefTable.setRowCount(0)
        self.gridLayout_3.addWidget(self.dupEsuRefTable, 0, 0, 1, 1)
        self.dupEsuRefLabel = QtGui.QLabel(self.dupEsuRefGroupBox)
        self.dupEsuRefLabel.setText(_fromUtf8(""))
        self.dupEsuRefLabel.setObjectName(_fromUtf8("dupEsuRefLabel"))
        self.gridLayout_3.addWidget(self.dupEsuRefLabel, 1, 0, 1, 1)
        self.horizontalLayout_5.addWidget(self.dupEsuRefGroupBox)
        self.notEsuStreetGroupBox = QtGui.QGroupBox(self.esuOptTab)
        self.notEsuStreetGroupBox.setObjectName(_fromUtf8("notEsuStreetGroupBox"))
        self.gridLayout_4 = QtGui.QGridLayout(self.notEsuStreetGroupBox)
        self.gridLayout_4.setObjectName(_fromUtf8("gridLayout_4"))
        self.notEsuStreetTable = QtGui.QTableWidget(self.notEsuStreetGroupBox)
        self.notEsuStreetTable.setEditTriggers(QtGui.QAbstractItemView.NoEditTriggers)
        self.notEsuStreetTable.setAlternatingRowColors(True)
        self.notEsuStreetTable.setSelectionMode(QtGui.QAbstractItemView.ContiguousSelection)
        self.notEsuStreetTable.setSelectionBehavior(QtGui.QAbstractItemView.SelectRows)
        self.notEsuStreetTable.setObjectName(_fromUtf8("notEsuStreetTable"))
        self.notEsuStreetTable.setColumnCount(0)
        self.notEsuStreetTable.setRowCount(0)
        self.gridLayout_4.addWidget(self.notEsuStreetTable, 0, 0, 1, 1)
        self.horizontalLayout_5.addWidget(self.notEsuStreetGroupBox)
        self.gridLayout_5.addLayout(self.horizontalLayout_5, 0, 0, 1, 1)
        self.invCrossRefGroupBox = QtGui.QGroupBox(self.esuOptTab)
        self.invCrossRefGroupBox.setObjectName(_fromUtf8("invCrossRefGroupBox"))
        self.gridLayout_2 = QtGui.QGridLayout(self.invCrossRefGroupBox)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.horizontalLayout_4 = QtGui.QHBoxLayout()
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        self.verticalLayout_8 = QtGui.QVBoxLayout()
        self.verticalLayout_8.setContentsMargins(0, -1, -1, -1)
        self.verticalLayout_8.setObjectName(_fromUtf8("verticalLayout_8"))
        self.type12StreetsTable = QtGui.QTableWidget(self.invCrossRefGroupBox)
        self.type12StreetsTable.setEditTriggers(QtGui.QAbstractItemView.NoEditTriggers)
        self.type12StreetsTable.setAlternatingRowColors(True)
        self.type12StreetsTable.setSelectionMode(QtGui.QAbstractItemView.ContiguousSelection)
        self.type12StreetsTable.setSelectionBehavior(QtGui.QAbstractItemView.SelectRows)
        self.type12StreetsTable.setObjectName(_fromUtf8("type12StreetsTable"))
        self.type12StreetsTable.setColumnCount(0)
        self.type12StreetsTable.setRowCount(0)
        self.verticalLayout_8.addWidget(self.type12StreetsTable)
        self.label = QtGui.QLabel(self.invCrossRefGroupBox)
        self.label.setWordWrap(True)
        self.label.setObjectName(_fromUtf8("label"))
        self.verticalLayout_8.addWidget(self.label)
        self.horizontalLayout_4.addLayout(self.verticalLayout_8)
        self.verticalLayout_5 = QtGui.QVBoxLayout()
        self.verticalLayout_5.setContentsMargins(0, -1, -1, -1)
        self.verticalLayout_5.setObjectName(_fromUtf8("verticalLayout_5"))
        self.type34StreetsTable = QtGui.QTableWidget(self.invCrossRefGroupBox)
        self.type34StreetsTable.setEditTriggers(QtGui.QAbstractItemView.NoEditTriggers)
        self.type34StreetsTable.setAlternatingRowColors(True)
        self.type34StreetsTable.setSelectionMode(QtGui.QAbstractItemView.ContiguousSelection)
        self.type34StreetsTable.setSelectionBehavior(QtGui.QAbstractItemView.SelectRows)
        self.type34StreetsTable.setObjectName(_fromUtf8("type34StreetsTable"))
        self.type34StreetsTable.setColumnCount(0)
        self.type34StreetsTable.setRowCount(0)
        self.verticalLayout_5.addWidget(self.type34StreetsTable)
        self.label_2 = QtGui.QLabel(self.invCrossRefGroupBox)
        self.label_2.setWordWrap(True)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.verticalLayout_5.addWidget(self.label_2)
        self.horizontalLayout_4.addLayout(self.verticalLayout_5)
        self.verticalLayout_4 = QtGui.QVBoxLayout()
        self.verticalLayout_4.setContentsMargins(0, -1, -1, -1)
        self.verticalLayout_4.setObjectName(_fromUtf8("verticalLayout_4"))
        self.unofficialTypeStreetsTable = QtGui.QTableWidget(self.invCrossRefGroupBox)
        self.unofficialTypeStreetsTable.setEditTriggers(QtGui.QAbstractItemView.NoEditTriggers)
        self.unofficialTypeStreetsTable.setAlternatingRowColors(True)
        self.unofficialTypeStreetsTable.setSelectionMode(QtGui.QAbstractItemView.ContiguousSelection)
        self.unofficialTypeStreetsTable.setSelectionBehavior(QtGui.QAbstractItemView.SelectRows)
        self.unofficialTypeStreetsTable.setObjectName(_fromUtf8("unofficialTypeStreetsTable"))
        self.unofficialTypeStreetsTable.setColumnCount(0)
        self.unofficialTypeStreetsTable.setRowCount(0)
        self.verticalLayout_4.addWidget(self.unofficialTypeStreetsTable)
        self.label_3 = QtGui.QLabel(self.invCrossRefGroupBox)
        self.label_3.setWordWrap(True)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.verticalLayout_4.addWidget(self.label_3)
        self.horizontalLayout_4.addLayout(self.verticalLayout_4)
        self.gridLayout_2.addLayout(self.horizontalLayout_4, 0, 0, 1, 1)
        self.gridLayout_5.addWidget(self.invCrossRefGroupBox, 1, 0, 1, 1)
        self.horizontalLayout_6 = QtGui.QHBoxLayout()
        self.horizontalLayout_6.setObjectName(_fromUtf8("horizontalLayout_6"))
        self.startEndGroupBox = QtGui.QGroupBox(self.esuOptTab)
        self.startEndGroupBox.setObjectName(_fromUtf8("startEndGroupBox"))
        self.gridLayout_6 = QtGui.QGridLayout(self.startEndGroupBox)
        self.gridLayout_6.setObjectName(_fromUtf8("gridLayout_6"))
        self.startEndTable = QtGui.QTableWidget(self.startEndGroupBox)
        self.startEndTable.setEditTriggers(QtGui.QAbstractItemView.NoEditTriggers)
        self.startEndTable.setAlternatingRowColors(True)
        self.startEndTable.setSelectionMode(QtGui.QAbstractItemView.ContiguousSelection)
        self.startEndTable.setSelectionBehavior(QtGui.QAbstractItemView.SelectRows)
        self.startEndTable.setObjectName(_fromUtf8("startEndTable"))
        self.startEndTable.setColumnCount(0)
        self.startEndTable.setRowCount(0)
        self.gridLayout_6.addWidget(self.startEndTable, 0, 0, 1, 1)
        self.toleranceLabel = QtGui.QLabel(self.startEndGroupBox)
        self.toleranceLabel.setMinimumSize(QtCore.QSize(0, 30))
        self.toleranceLabel.setMaximumSize(QtCore.QSize(225, 30))
        self.toleranceLabel.setWordWrap(True)
        self.toleranceLabel.setObjectName(_fromUtf8("toleranceLabel"))
        self.gridLayout_6.addWidget(self.toleranceLabel, 1, 0, 1, 1)
        self.horizontalLayout_6.addWidget(self.startEndGroupBox)
        self.tinyEsuGroupBox = QtGui.QGroupBox(self.esuOptTab)
        self.tinyEsuGroupBox.setObjectName(_fromUtf8("tinyEsuGroupBox"))
        self.gridLayout_10 = QtGui.QGridLayout(self.tinyEsuGroupBox)
        self.gridLayout_10.setObjectName(_fromUtf8("gridLayout_10"))
        self.tinyEsuTable = QtGui.QTableWidget(self.tinyEsuGroupBox)
        self.tinyEsuTable.setEditTriggers(QtGui.QAbstractItemView.NoEditTriggers)
        self.tinyEsuTable.setAlternatingRowColors(True)
        self.tinyEsuTable.setSelectionMode(QtGui.QAbstractItemView.ContiguousSelection)
        self.tinyEsuTable.setSelectionBehavior(QtGui.QAbstractItemView.SelectRows)
        self.tinyEsuTable.setObjectName(_fromUtf8("tinyEsuTable"))
        self.tinyEsuTable.setColumnCount(0)
        self.tinyEsuTable.setRowCount(0)
        self.gridLayout_10.addWidget(self.tinyEsuTable, 0, 0, 1, 1)
        self.horizontalLayout_6.addWidget(self.tinyEsuGroupBox)
        self.noGeomEsuGroupBox = QtGui.QGroupBox(self.esuOptTab)
        self.noGeomEsuGroupBox.setObjectName(_fromUtf8("noGeomEsuGroupBox"))
        self.gridLayout_11 = QtGui.QGridLayout(self.noGeomEsuGroupBox)
        self.gridLayout_11.setObjectName(_fromUtf8("gridLayout_11"))
        self.noGeomEsuTable = QtGui.QTableWidget(self.noGeomEsuGroupBox)
        self.noGeomEsuTable.setEditTriggers(QtGui.QAbstractItemView.NoEditTriggers)
        self.noGeomEsuTable.setAlternatingRowColors(True)
        self.noGeomEsuTable.setSelectionMode(QtGui.QAbstractItemView.ContiguousSelection)
        self.noGeomEsuTable.setSelectionBehavior(QtGui.QAbstractItemView.SelectRows)
        self.noGeomEsuTable.setObjectName(_fromUtf8("noGeomEsuTable"))
        self.noGeomEsuTable.setColumnCount(0)
        self.noGeomEsuTable.setRowCount(0)
        self.gridLayout_11.addWidget(self.noGeomEsuTable, 0, 0, 1, 1)
        self.horizontalLayout_6.addWidget(self.noGeomEsuGroupBox)
        self.gridLayout_5.addLayout(self.horizontalLayout_6, 2, 0, 1, 1)
        self.tabWidget.addTab(self.esuOptTab, _fromUtf8(""))
        self.asdOptTab = QtGui.QWidget()
        self.asdOptTab.setObjectName(_fromUtf8("asdOptTab"))
        self.gridLayout_15 = QtGui.QGridLayout(self.asdOptTab)
        self.gridLayout_15.setObjectName(_fromUtf8("gridLayout_15"))
        self.horizontalLayout_7 = QtGui.QHBoxLayout()
        self.horizontalLayout_7.setObjectName(_fromUtf8("horizontalLayout_7"))
        self.notMaintGroupBox = QtGui.QGroupBox(self.asdOptTab)
        self.notMaintGroupBox.setObjectName(_fromUtf8("notMaintGroupBox"))
        self.gridLayout_8 = QtGui.QGridLayout(self.notMaintGroupBox)
        self.gridLayout_8.setObjectName(_fromUtf8("gridLayout_8"))
        self.notMaintTable = QtGui.QTableWidget(self.notMaintGroupBox)
        self.notMaintTable.setEditTriggers(QtGui.QAbstractItemView.NoEditTriggers)
        self.notMaintTable.setAlternatingRowColors(True)
        self.notMaintTable.setSelectionMode(QtGui.QAbstractItemView.ContiguousSelection)
        self.notMaintTable.setSelectionBehavior(QtGui.QAbstractItemView.SelectRows)
        self.notMaintTable.setObjectName(_fromUtf8("notMaintTable"))
        self.notMaintTable.setColumnCount(0)
        self.notMaintTable.setRowCount(0)
        self.gridLayout_8.addWidget(self.notMaintTable, 0, 0, 1, 1)
        self.horizontalLayout_7.addWidget(self.notMaintGroupBox)
        self.notReinsGroupBox = QtGui.QGroupBox(self.asdOptTab)
        self.notReinsGroupBox.setObjectName(_fromUtf8("notReinsGroupBox"))
        self.gridLayout_9 = QtGui.QGridLayout(self.notReinsGroupBox)
        self.gridLayout_9.setObjectName(_fromUtf8("gridLayout_9"))
        self.notReinsTable = QtGui.QTableWidget(self.notReinsGroupBox)
        self.notReinsTable.setEditTriggers(QtGui.QAbstractItemView.NoEditTriggers)
        self.notReinsTable.setAlternatingRowColors(True)
        self.notReinsTable.setSelectionMode(QtGui.QAbstractItemView.ContiguousSelection)
        self.notReinsTable.setSelectionBehavior(QtGui.QAbstractItemView.SelectRows)
        self.notReinsTable.setObjectName(_fromUtf8("notReinsTable"))
        self.notReinsTable.setColumnCount(0)
        self.notReinsTable.setRowCount(0)
        self.gridLayout_9.addWidget(self.notReinsTable, 0, 0, 1, 1)
        self.horizontalLayout_7.addWidget(self.notReinsGroupBox)
        self.gridLayout_15.addLayout(self.horizontalLayout_7, 0, 0, 1, 1)
        self.horizontalLayout_8 = QtGui.QHBoxLayout()
        self.horizontalLayout_8.setObjectName(_fromUtf8("horizontalLayout_8"))
        self.asdMaintCoordGroupBox = QtGui.QGroupBox(self.asdOptTab)
        self.asdMaintCoordGroupBox.setObjectName(_fromUtf8("asdMaintCoordGroupBox"))
        self.gridLayout_12 = QtGui.QGridLayout(self.asdMaintCoordGroupBox)
        self.gridLayout_12.setObjectName(_fromUtf8("gridLayout_12"))
        self.asdMaintCoordTable = QtGui.QTableWidget(self.asdMaintCoordGroupBox)
        self.asdMaintCoordTable.setEditTriggers(QtGui.QAbstractItemView.NoEditTriggers)
        self.asdMaintCoordTable.setAlternatingRowColors(True)
        self.asdMaintCoordTable.setSelectionMode(QtGui.QAbstractItemView.ContiguousSelection)
        self.asdMaintCoordTable.setSelectionBehavior(QtGui.QAbstractItemView.SelectRows)
        self.asdMaintCoordTable.setObjectName(_fromUtf8("asdMaintCoordTable"))
        self.asdMaintCoordTable.setColumnCount(0)
        self.asdMaintCoordTable.setRowCount(0)
        self.gridLayout_12.addWidget(self.asdMaintCoordTable, 0, 0, 1, 1)
        self.horizontalLayout_8.addWidget(self.asdMaintCoordGroupBox)
        self.asdSpecDesCoordGroupBox = QtGui.QGroupBox(self.asdOptTab)
        self.asdSpecDesCoordGroupBox.setObjectName(_fromUtf8("asdSpecDesCoordGroupBox"))
        self.gridLayout_13 = QtGui.QGridLayout(self.asdSpecDesCoordGroupBox)
        self.gridLayout_13.setObjectName(_fromUtf8("gridLayout_13"))
        self.asdSpecDesCoordTable = QtGui.QTableWidget(self.asdSpecDesCoordGroupBox)
        self.asdSpecDesCoordTable.setEditTriggers(QtGui.QAbstractItemView.NoEditTriggers)
        self.asdSpecDesCoordTable.setAlternatingRowColors(True)
        self.asdSpecDesCoordTable.setSelectionMode(QtGui.QAbstractItemView.ContiguousSelection)
        self.asdSpecDesCoordTable.setSelectionBehavior(QtGui.QAbstractItemView.SelectRows)
        self.asdSpecDesCoordTable.setObjectName(_fromUtf8("asdSpecDesCoordTable"))
        self.asdSpecDesCoordTable.setColumnCount(0)
        self.asdSpecDesCoordTable.setRowCount(0)
        self.gridLayout_13.addWidget(self.asdSpecDesCoordTable, 0, 0, 1, 1)
        self.horizontalLayout_8.addWidget(self.asdSpecDesCoordGroupBox)
        self.asdReinsCoordGroupBox = QtGui.QGroupBox(self.asdOptTab)
        self.asdReinsCoordGroupBox.setObjectName(_fromUtf8("asdReinsCoordGroupBox"))
        self.gridLayout_14 = QtGui.QGridLayout(self.asdReinsCoordGroupBox)
        self.gridLayout_14.setObjectName(_fromUtf8("gridLayout_14"))
        self.asdReinsCoordTable = QtGui.QTableWidget(self.asdReinsCoordGroupBox)
        self.asdReinsCoordTable.setEditTriggers(QtGui.QAbstractItemView.NoEditTriggers)
        self.asdReinsCoordTable.setAlternatingRowColors(True)
        self.asdReinsCoordTable.setSelectionMode(QtGui.QAbstractItemView.ContiguousSelection)
        self.asdReinsCoordTable.setSelectionBehavior(QtGui.QAbstractItemView.SelectRows)
        self.asdReinsCoordTable.setObjectName(_fromUtf8("asdReinsCoordTable"))
        self.asdReinsCoordTable.setColumnCount(0)
        self.asdReinsCoordTable.setRowCount(0)
        self.gridLayout_14.addWidget(self.asdReinsCoordTable, 0, 0, 1, 1)
        self.horizontalLayout_8.addWidget(self.asdReinsCoordGroupBox)
        self.gridLayout_15.addLayout(self.horizontalLayout_8, 1, 0, 1, 1)
        self.tabWidget.addTab(self.asdOptTab, _fromUtf8(""))
        self.polyOptTab = QtGui.QWidget()
        self.polyOptTab.setObjectName(_fromUtf8("polyOptTab"))
        self.gridLayout_22 = QtGui.QGridLayout(self.polyOptTab)
        self.gridLayout_22.setObjectName(_fromUtf8("gridLayout_22"))
        self.gridLayout_21 = QtGui.QGridLayout()
        self.gridLayout_21.setObjectName(_fromUtf8("gridLayout_21"))
        self.horizontalLayout_9 = QtGui.QHBoxLayout()
        self.horizontalLayout_9.setObjectName(_fromUtf8("horizontalLayout_9"))
        self.maintRecGroupBox = QtGui.QGroupBox(self.polyOptTab)
        self.maintRecGroupBox.setObjectName(_fromUtf8("maintRecGroupBox"))
        self.gridLayout_16 = QtGui.QGridLayout(self.maintRecGroupBox)
        self.gridLayout_16.setObjectName(_fromUtf8("gridLayout_16"))
        self.maintRecTable = QtGui.QTableWidget(self.maintRecGroupBox)
        self.maintRecTable.setEditTriggers(QtGui.QAbstractItemView.NoEditTriggers)
        self.maintRecTable.setAlternatingRowColors(True)
        self.maintRecTable.setSelectionMode(QtGui.QAbstractItemView.ContiguousSelection)
        self.maintRecTable.setSelectionBehavior(QtGui.QAbstractItemView.SelectRows)
        self.maintRecTable.setObjectName(_fromUtf8("maintRecTable"))
        self.maintRecTable.setColumnCount(0)
        self.maintRecTable.setRowCount(0)
        self.gridLayout_16.addWidget(self.maintRecTable, 0, 0, 1, 1)
        self.horizontalLayout_9.addWidget(self.maintRecGroupBox)
        self.polyMaintGroupBox = QtGui.QGroupBox(self.polyOptTab)
        self.polyMaintGroupBox.setObjectName(_fromUtf8("polyMaintGroupBox"))
        self.gridLayout_17 = QtGui.QGridLayout(self.polyMaintGroupBox)
        self.gridLayout_17.setObjectName(_fromUtf8("gridLayout_17"))
        self.polyMaintTable = QtGui.QTableWidget(self.polyMaintGroupBox)
        self.polyMaintTable.setEditTriggers(QtGui.QAbstractItemView.NoEditTriggers)
        self.polyMaintTable.setAlternatingRowColors(True)
        self.polyMaintTable.setSelectionMode(QtGui.QAbstractItemView.ContiguousSelection)
        self.polyMaintTable.setSelectionBehavior(QtGui.QAbstractItemView.SelectRows)
        self.polyMaintTable.setObjectName(_fromUtf8("polyMaintTable"))
        self.polyMaintTable.setColumnCount(0)
        self.polyMaintTable.setRowCount(0)
        self.gridLayout_17.addWidget(self.polyMaintTable, 0, 0, 1, 1)
        self.horizontalLayout_9.addWidget(self.polyMaintGroupBox)
        self.gridLayout_21.addLayout(self.horizontalLayout_9, 0, 0, 1, 1)
        self.horizontalLayout_10 = QtGui.QHBoxLayout()
        self.horizontalLayout_10.setObjectName(_fromUtf8("horizontalLayout_10"))
        self.multiPolyGroupBox = QtGui.QGroupBox(self.polyOptTab)
        self.multiPolyGroupBox.setObjectName(_fromUtf8("multiPolyGroupBox"))
        self.gridLayout_18 = QtGui.QGridLayout(self.multiPolyGroupBox)
        self.gridLayout_18.setObjectName(_fromUtf8("gridLayout_18"))
        self.multiPolyTable = QtGui.QTableWidget(self.multiPolyGroupBox)
        self.multiPolyTable.setEditTriggers(QtGui.QAbstractItemView.NoEditTriggers)
        self.multiPolyTable.setAlternatingRowColors(True)
        self.multiPolyTable.setSelectionMode(QtGui.QAbstractItemView.ContiguousSelection)
        self.multiPolyTable.setSelectionBehavior(QtGui.QAbstractItemView.SelectRows)
        self.multiPolyTable.setObjectName(_fromUtf8("multiPolyTable"))
        self.multiPolyTable.setColumnCount(0)
        self.multiPolyTable.setRowCount(0)
        self.gridLayout_18.addWidget(self.multiPolyTable, 0, 0, 1, 1)
        self.horizontalLayout_10.addWidget(self.multiPolyGroupBox)
        self.tinyPolysGroupBox = QtGui.QGroupBox(self.polyOptTab)
        self.tinyPolysGroupBox.setObjectName(_fromUtf8("tinyPolysGroupBox"))
        self.gridLayout_19 = QtGui.QGridLayout(self.tinyPolysGroupBox)
        self.gridLayout_19.setObjectName(_fromUtf8("gridLayout_19"))
        self.tinyPolysTable = QtGui.QTableWidget(self.tinyPolysGroupBox)
        self.tinyPolysTable.setEditTriggers(QtGui.QAbstractItemView.NoEditTriggers)
        self.tinyPolysTable.setAlternatingRowColors(True)
        self.tinyPolysTable.setSelectionMode(QtGui.QAbstractItemView.ContiguousSelection)
        self.tinyPolysTable.setSelectionBehavior(QtGui.QAbstractItemView.SelectRows)
        self.tinyPolysTable.setObjectName(_fromUtf8("tinyPolysTable"))
        self.tinyPolysTable.setColumnCount(0)
        self.tinyPolysTable.setRowCount(0)
        self.gridLayout_19.addWidget(self.tinyPolysTable, 0, 0, 1, 1)
        self.horizontalLayout_10.addWidget(self.tinyPolysGroupBox)
        self.noGeomPolysGroupBox = QtGui.QGroupBox(self.polyOptTab)
        self.noGeomPolysGroupBox.setObjectName(_fromUtf8("noGeomPolysGroupBox"))
        self.gridLayout_20 = QtGui.QGridLayout(self.noGeomPolysGroupBox)
        self.gridLayout_20.setObjectName(_fromUtf8("gridLayout_20"))
        self.noGeomPolysTable = QtGui.QTableWidget(self.noGeomPolysGroupBox)
        self.noGeomPolysTable.setEditTriggers(QtGui.QAbstractItemView.NoEditTriggers)
        self.noGeomPolysTable.setAlternatingRowColors(True)
        self.noGeomPolysTable.setSelectionMode(QtGui.QAbstractItemView.ContiguousSelection)
        self.noGeomPolysTable.setSelectionBehavior(QtGui.QAbstractItemView.SelectRows)
        self.noGeomPolysTable.setObjectName(_fromUtf8("noGeomPolysTable"))
        self.noGeomPolysTable.setColumnCount(0)
        self.noGeomPolysTable.setRowCount(0)
        self.gridLayout_20.addWidget(self.noGeomPolysTable, 0, 0, 1, 1)
        self.horizontalLayout_10.addWidget(self.noGeomPolysGroupBox)
        self.gridLayout_21.addLayout(self.horizontalLayout_10, 1, 0, 1, 1)
        self.gridLayout_22.addLayout(self.gridLayout_21, 0, 0, 1, 1)
        self.tabWidget.addTab(self.polyOptTab, _fromUtf8(""))
        self.gridLayout_7.addWidget(self.tabWidget, 0, 0, 1, 1)

        self.retranslateUi(validationSummaryDialog)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(validationSummaryDialog)

    def retranslateUi(self, validationSummaryDialog):
        validationSummaryDialog.setWindowTitle(_translate("validationSummaryDialog", "Validation Report Summary", None))
        self.groupBox.setTitle(_translate("validationSummaryDialog", "Duplicate street descriptions", None))
        self.dupDesTable.setSortingEnabled(False)
        self.groupBox_2.setTitle(_translate("validationSummaryDialog", "Streets not linked to ESU", None))
        self.type3GroupBox.setTitle(_translate("validationSummaryDialog", "Streets without Type 3", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.streetOptTab), _translate("validationSummaryDialog", "Street Options", None))
        self.dupEsuRefGroupBox.setTitle(_translate("validationSummaryDialog", "Duplicate ESU references", None))
        self.dupEsuRefTable.setSortingEnabled(False)
        self.notEsuStreetGroupBox.setTitle(_translate("validationSummaryDialog", "ESUs not linked to street", None))
        self.notEsuStreetTable.setSortingEnabled(False)
        self.invCrossRefGroupBox.setTitle(_translate("validationSummaryDialog", "Invalid cross-references", None))
        self.type12StreetsTable.setSortingEnabled(False)
        self.label.setText(_translate("validationSummaryDialog", "ESUs incorrectly linked to Type 1 and Type 2 streets", None))
        self.type34StreetsTable.setSortingEnabled(False)
        self.label_2.setText(_translate("validationSummaryDialog", "ESUs linked to Type 3 or 4 streets but not to Type 1 or 2", None))
        self.unofficialTypeStreetsTable.setSortingEnabled(False)
        self.label_3.setText(_translate("validationSummaryDialog", "ESUs linked to unofficial street types (ie. not 1,2,3or4)", None))
        self.startEndGroupBox.setTitle(_translate("validationSummaryDialog", "Start + end coordinates", None))
        self.startEndTable.setSortingEnabled(False)
        self.toleranceLabel.setText(_translate("validationSummaryDialog", "Streets with misplaced start/end coordinates. Tolerance: ", None))
        self.tinyEsuGroupBox.setTitle(_translate("validationSummaryDialog", "Tiny ESUs", None))
        self.tinyEsuTable.setSortingEnabled(False)
        self.noGeomEsuGroupBox.setTitle(_translate("validationSummaryDialog", "ESUs with invalid geometry", None))
        self.noGeomEsuTable.setSortingEnabled(False)
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.esuOptTab), _translate("validationSummaryDialog", "ESU Options", None))
        self.notMaintGroupBox.setTitle(_translate("validationSummaryDialog", "Type 1/2 streets not linked to maintenance records", None))
        self.notMaintTable.setSortingEnabled(False)
        self.notReinsGroupBox.setTitle(_translate("validationSummaryDialog", "Type 1/2 streets not linked to reinstatement records", None))
        self.notReinsTable.setSortingEnabled(False)
        self.asdMaintCoordGroupBox.setTitle(_translate("validationSummaryDialog", "Maintenance records with invalid start-end coordinates", None))
        self.asdMaintCoordTable.setSortingEnabled(False)
        self.asdSpecDesCoordGroupBox.setTitle(_translate("validationSummaryDialog", "Special designation records with invalid start-end coordinates", None))
        self.asdSpecDesCoordTable.setSortingEnabled(False)
        self.asdReinsCoordGroupBox.setTitle(_translate("validationSummaryDialog", "Reinstatement records with invalid start-end coordinates", None))
        self.asdReinsCoordTable.setSortingEnabled(False)
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.asdOptTab), _translate("validationSummaryDialog", "ASD Options", None))
        self.maintRecGroupBox.setTitle(_translate("validationSummaryDialog", "Maintenance records not linked to any polygons", None))
        self.maintRecTable.setSortingEnabled(False)
        self.polyMaintGroupBox.setTitle(_translate("validationSummaryDialog", "Polygons not linked to a maintenance record", None))
        self.polyMaintTable.setSortingEnabled(False)
        self.multiPolyGroupBox.setTitle(_translate("validationSummaryDialog", "Polygons wrongly assigned to more than one maintenance record", None))
        self.multiPolyTable.setSortingEnabled(False)
        self.tinyPolysGroupBox.setTitle(_translate("validationSummaryDialog", "Tiny polygons", None))
        self.tinyPolysTable.setSortingEnabled(False)
        self.noGeomPolysGroupBox.setTitle(_translate("validationSummaryDialog", "Polygons with invalid geometry", None))
        self.noGeomPolysTable.setSortingEnabled(False)
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.polyOptTab), _translate("validationSummaryDialog", "Polygon Options", None))

