# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'gui\rn_export_lor_ui.ui'
#
# Created: Tue Nov 17 16:28:15 2015
#      by: PyQt4 UI code generator 4.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_exportLorDialog(object):
    def setupUi(self, exportLorDialog):
        exportLorDialog.setObjectName(_fromUtf8("exportLorDialog"))
        exportLorDialog.resize(353, 417)
        exportLorDialog.setMinimumSize(QtCore.QSize(353, 417))
        exportLorDialog.setMaximumSize(QtCore.QSize(353, 417))
        exportLorDialog.setWindowFlags(QtCore.Qt.CustomizeWindowHint | QtCore.Qt.WindowTitleHint)
        self.gridLayout_4 = QtGui.QGridLayout(exportLorDialog)
        self.gridLayout_4.setObjectName(_fromUtf8("gridLayout_4"))
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.fileLabel = QtGui.QLabel(exportLorDialog)
        self.fileLabel.setObjectName(_fromUtf8("fileLabel"))
        self.horizontalLayout.addWidget(self.fileLabel)
        self.fileLineEdit = QtGui.QLineEdit(exportLorDialog)
        self.fileLineEdit.setObjectName(_fromUtf8("fileLineEdit"))
        self.horizontalLayout.addWidget(self.fileLineEdit)
        self.openPushButton = QtGui.QPushButton(exportLorDialog)
        self.openPushButton.setText(_fromUtf8(""))
        self.openPushButton.setObjectName(_fromUtf8("openPushButton"))
        self.horizontalLayout.addWidget(self.openPushButton)
        self.gridLayout_4.addLayout(self.horizontalLayout, 0, 0, 1, 1)
        self.label_4 = QtGui.QLabel(exportLorDialog)
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setWordWrap(True)
        self.label_4.setIndent(7)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.gridLayout_4.addWidget(self.label_4, 1, 0, 1, 1)
        self.groupBox = QtGui.QGroupBox(exportLorDialog)
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self.gridLayout = QtGui.QGridLayout(self.groupBox)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.verticalLayout = QtGui.QVBoxLayout()
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.horizontalLayout_10 = QtGui.QHBoxLayout()
        self.horizontalLayout_10.setSizeConstraint(QtGui.QLayout.SetNoConstraint)
        self.horizontalLayout_10.setObjectName(_fromUtf8("horizontalLayout_10"))
        spacerItem = QtGui.QSpacerItem(20, 20, QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_10.addItem(spacerItem)
        self.publicRadioButton = QtGui.QRadioButton(self.groupBox)
        self.publicRadioButton.setEnabled(True)
        self.publicRadioButton.setObjectName(_fromUtf8("publicRadioButton"))
        self.horizontalLayout_10.addWidget(self.publicRadioButton)
        spacerItem1 = QtGui.QSpacerItem(25, 20, QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_10.addItem(spacerItem1)
        self.anyRadioButton = QtGui.QRadioButton(self.groupBox)
        self.anyRadioButton.setObjectName(_fromUtf8("anyRadioButton"))
        self.horizontalLayout_10.addWidget(self.anyRadioButton)
        self.verticalLayout.addLayout(self.horizontalLayout_10)
        self.horizontalLayout_7 = QtGui.QHBoxLayout()
        self.horizontalLayout_7.setSpacing(36)
        self.horizontalLayout_7.setContentsMargins(27, 5, 3, 3)
        self.horizontalLayout_7.setObjectName(_fromUtf8("horizontalLayout_7"))
        self.publicCheckBox = QtGui.QCheckBox(self.groupBox)
        self.publicCheckBox.setObjectName(_fromUtf8("publicCheckBox"))
        self.horizontalLayout_7.addWidget(self.publicCheckBox)
        self.proPublicCheckBox = QtGui.QCheckBox(self.groupBox)
        self.proPublicCheckBox.setObjectName(_fromUtf8("proPublicCheckBox"))
        self.horizontalLayout_7.addWidget(self.proPublicCheckBox)
        self.verticalLayout.addLayout(self.horizontalLayout_7)
        self.horizontalLayout_11 = QtGui.QHBoxLayout()
        self.horizontalLayout_11.setSpacing(36)
        self.horizontalLayout_11.setContentsMargins(27, 5, 3, 3)
        self.horizontalLayout_11.setObjectName(_fromUtf8("horizontalLayout_11"))
        self.t3CheckBox = QtGui.QCheckBox(self.groupBox)
        self.t3CheckBox.setObjectName(_fromUtf8("t3CheckBox"))
        self.horizontalLayout_11.addWidget(self.t3CheckBox)
        self.t4CheckBox = QtGui.QCheckBox(self.groupBox)
        self.t4CheckBox.setObjectName(_fromUtf8("t4CheckBox"))
        self.horizontalLayout_11.addWidget(self.t4CheckBox)
        self.verticalLayout.addLayout(self.horizontalLayout_11)
        self.horizontalLayout_12 = QtGui.QHBoxLayout()
        self.horizontalLayout_12.setSpacing(36)
        self.horizontalLayout_12.setContentsMargins(27, 5, 3, 3)
        self.horizontalLayout_12.setObjectName(_fromUtf8("horizontalLayout_12"))
        self.privateCheckBox = QtGui.QCheckBox(self.groupBox)
        self.privateCheckBox.setObjectName(_fromUtf8("privateCheckBox"))
        self.horizontalLayout_12.addWidget(self.privateCheckBox)
        self.trunkCheckBox = QtGui.QCheckBox(self.groupBox)
        self.trunkCheckBox.setObjectName(_fromUtf8("trunkCheckBox"))
        self.horizontalLayout_12.addWidget(self.trunkCheckBox)
        self.verticalLayout.addLayout(self.horizontalLayout_12)
        self.gridLayout.addLayout(self.verticalLayout, 0, 0, 1, 1)
        self.gridLayout_4.addWidget(self.groupBox, 2, 0, 1, 1)
        self.groupBox_2 = QtGui.QGroupBox(exportLorDialog)
        self.groupBox_2.setObjectName(_fromUtf8("groupBox_2"))
        self.gridLayout_2 = QtGui.QGridLayout(self.groupBox_2)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.horizontalLayout_8 = QtGui.QHBoxLayout()
        self.horizontalLayout_8.setSpacing(36)
        self.horizontalLayout_8.setContentsMargins(27, 5, 3, 3)
        self.horizontalLayout_8.setObjectName(_fromUtf8("horizontalLayout_8"))
        self.lorNoCeckBox = QtGui.QCheckBox(self.groupBox_2)
        self.lorNoCeckBox.setObjectName(_fromUtf8("lorNoCeckBox"))
        self.horizontalLayout_8.addWidget(self.lorNoCeckBox)
        self.usrnCheckBox = QtGui.QCheckBox(self.groupBox_2)
        self.usrnCheckBox.setObjectName(_fromUtf8("usrnCheckBox"))
        self.horizontalLayout_8.addWidget(self.usrnCheckBox)
        self.gridLayout_2.addLayout(self.horizontalLayout_8, 0, 0, 1, 1)
        self.gridLayout_4.addWidget(self.groupBox_2, 3, 0, 1, 1)
        self.groupBox_3 = QtGui.QGroupBox(exportLorDialog)
        self.groupBox_3.setObjectName(_fromUtf8("groupBox_3"))
        self.gridLayout_3 = QtGui.QGridLayout(self.groupBox_3)
        self.gridLayout_3.setObjectName(_fromUtf8("gridLayout_3"))
        self.horizontalLayout_9 = QtGui.QHBoxLayout()
        self.horizontalLayout_9.setObjectName(_fromUtf8("horizontalLayout_9"))
        self.townCheckBox = QtGui.QCheckBox(self.groupBox_3)
        self.townCheckBox.setObjectName(_fromUtf8("townCheckBox"))
        self.horizontalLayout_9.addWidget(self.townCheckBox)
        spacerItem2 = QtGui.QSpacerItem(25, 20, QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_9.addItem(spacerItem2)
        self.csvCheckBox = QtGui.QCheckBox(self.groupBox_3)
        self.csvCheckBox.setObjectName(_fromUtf8("csvCheckBox"))
        self.horizontalLayout_9.addWidget(self.csvCheckBox)
        self.gridLayout_3.addLayout(self.horizontalLayout_9, 0, 1, 1, 1)
        spacerItem3 = QtGui.QSpacerItem(18, 20, QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Minimum)
        self.gridLayout_3.addItem(spacerItem3, 0, 0, 1, 1)
        self.gridLayout_4.addWidget(self.groupBox_3, 4, 0, 1, 1)
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        spacerItem4 = QtGui.QSpacerItem(214, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem4)
        self.okPushButton = QtGui.QPushButton(exportLorDialog)
        self.okPushButton.setObjectName(_fromUtf8("okPushButton"))
        self.horizontalLayout_3.addWidget(self.okPushButton)
        self.cancelPushButton = QtGui.QPushButton(exportLorDialog)
        self.cancelPushButton.setObjectName(_fromUtf8("cancelPushButton"))
        self.horizontalLayout_3.addWidget(self.cancelPushButton)
        self.gridLayout_4.addLayout(self.horizontalLayout_3, 5, 0, 1, 1)

        self.retranslateUi(exportLorDialog)
        QtCore.QMetaObject.connectSlotsByName(exportLorDialog)

    def retranslateUi(self, exportLorDialog):
        exportLorDialog.setWindowTitle(_translate("exportLorDialog", "Export List of Roads", None))
        self.fileLabel.setText(_translate("exportLorDialog", "Export To", None))
        self.label_4.setText(_translate("exportLorDialog", "Default settings report Name, Town, Status and Description for Public Type 1 + 2 streets.", None))
        self.groupBox.setTitle(_translate("exportLorDialog", "Records", None))
        self.publicRadioButton.setText(_translate("exportLorDialog", "Public Only", None))
        self.anyRadioButton.setText(_translate("exportLorDialog", "Any Status", None))
        self.publicCheckBox.setText(_translate("exportLorDialog", "Public", None))
        self.proPublicCheckBox.setText(_translate("exportLorDialog", "Prospective Public", None))
        self.t3CheckBox.setText(_translate("exportLorDialog", "Include Type 3", None))
        self.t4CheckBox.setText(_translate("exportLorDialog", "Include Type 4", None))
        self.privateCheckBox.setText(_translate("exportLorDialog", "Private", None))
        self.trunkCheckBox.setText(_translate("exportLorDialog", "Trunk", None))
        self.groupBox_2.setTitle(_translate("exportLorDialog", "Additional Info", None))
        self.lorNoCeckBox.setText(_translate("exportLorDialog", "Include LOR No", None))
        self.usrnCheckBox.setText(_translate("exportLorDialog", "USRN", None))
        self.groupBox_3.setTitle(_translate("exportLorDialog", "Format Options", None))
        self.townCheckBox.setText(_translate("exportLorDialog", "Sort By Town", None))
        self.csvCheckBox.setText(_translate("exportLorDialog", "CSV Formatted", None))
        self.okPushButton.setText(_translate("exportLorDialog", "OK", None))
        self.cancelPushButton.setText(_translate("exportLorDialog", "Cancel", None))


if __name__ == "__main__":
    import sys
    app = QtGui.QApplication(sys.argv)
    exportLorDialog = QtGui.QDialog()
    ui = Ui_exportLorDialog()
    ui.setupUi(exportLorDialog)
    exportLorDialog.show()
    sys.exit(app.exec_())

