# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'gui\rn_street_browser_ui.ui'
#
# Created: Thu Dec 31 20:34:34 2015
#      by: PyQt4 UI code generator 4.10.2
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_streetBrowserDialog(object):
    def setupUi(self, streetBrowserDialog):
        streetBrowserDialog.setObjectName(_fromUtf8("streetBrowserDialog"))
        streetBrowserDialog.resize(1212, 650)
        streetBrowserDialog.setMinimumSize(QtCore.QSize(1212, 650))
        streetBrowserDialog.setMaximumSize(QtCore.QSize(16777215, 16777215))
        streetBrowserDialog.setBaseSize(QtCore.QSize(1212, 700))
        self.gridLayout_32 = QtGui.QGridLayout(streetBrowserDialog)
        self.gridLayout_32.setSpacing(0)
        self.gridLayout_32.setMargin(0)
        self.gridLayout_32.setObjectName(_fromUtf8("gridLayout_32"))
        self.scrollArea = QtGui.QScrollArea(streetBrowserDialog)
        self.scrollArea.setFrameShape(QtGui.QFrame.NoFrame)
        self.scrollArea.setFrameShadow(QtGui.QFrame.Plain)
        self.scrollArea.setLineWidth(0)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName(_fromUtf8("scrollArea"))
        self.scrollAreaWidgetContents = QtGui.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 1195, 1001))
        self.scrollAreaWidgetContents.setObjectName(_fromUtf8("scrollAreaWidgetContents"))
        self.gridLayout_34 = QtGui.QGridLayout(self.scrollAreaWidgetContents)
        self.gridLayout_34.setObjectName(_fromUtf8("gridLayout_34"))
        self.srwrRecordsGroupBox = QtGui.QGroupBox(self.scrollAreaWidgetContents)
        self.srwrRecordsGroupBox.setEnabled(True)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.srwrRecordsGroupBox.sizePolicy().hasHeightForWidth())
        self.srwrRecordsGroupBox.setSizePolicy(sizePolicy)
        self.srwrRecordsGroupBox.setMinimumSize(QtCore.QSize(861, 0))
        self.srwrRecordsGroupBox.setObjectName(_fromUtf8("srwrRecordsGroupBox"))
        self.gridLayout_33 = QtGui.QGridLayout(self.srwrRecordsGroupBox)
        self.gridLayout_33.setObjectName(_fromUtf8("gridLayout_33"))
        self.srwrTabWidget = QtGui.QTabWidget(self.srwrRecordsGroupBox)
        self.srwrTabWidget.setEnabled(True)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.srwrTabWidget.sizePolicy().hasHeightForWidth())
        self.srwrTabWidget.setSizePolicy(sizePolicy)
        self.srwrTabWidget.setMinimumSize(QtCore.QSize(0, 250))
        self.srwrTabWidget.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.srwrTabWidget.setTabShape(QtGui.QTabWidget.Rounded)
        self.srwrTabWidget.setIconSize(QtCore.QSize(16, 16))
        self.srwrTabWidget.setUsesScrollButtons(True)
        self.srwrTabWidget.setDocumentMode(False)
        self.srwrTabWidget.setObjectName(_fromUtf8("srwrTabWidget"))
        self.maintenanceTab = QtGui.QWidget()
        self.maintenanceTab.setObjectName(_fromUtf8("maintenanceTab"))
        self.gridLayout_13 = QtGui.QGridLayout(self.maintenanceTab)
        self.gridLayout_13.setObjectName(_fromUtf8("gridLayout_13"))
        self.maintTableView = QtGui.QTableView(self.maintenanceTab)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("MS Shell Dlg 2"))
        font.setPointSize(8)
        self.maintTableView.setFont(font)
        self.maintTableView.setStyleSheet(_fromUtf8("border-width:0.5px;\n"
"border-style: solid;\n"
"border-radius: 2px;\n"
"border-color:  rgb(100,100,100);\n"
"background-color: rgb(213, 234, 234);"))
        self.maintTableView.setEditTriggers(QtGui.QAbstractItemView.NoEditTriggers)
        self.maintTableView.setAlternatingRowColors(False)
        self.maintTableView.setSelectionMode(QtGui.QAbstractItemView.SingleSelection)
        self.maintTableView.setSelectionBehavior(QtGui.QAbstractItemView.SelectRows)
        self.maintTableView.setObjectName(_fromUtf8("maintTableView"))
        self.maintTableView.horizontalHeader().setStretchLastSection(True)
        self.maintTableView.verticalHeader().setVisible(False)
        self.gridLayout_13.addWidget(self.maintTableView, 0, 0, 1, 1)
        self.srwrTabWidget.addTab(self.maintenanceTab, _fromUtf8(""))
        self.specialDesignationsTab = QtGui.QWidget()
        self.specialDesignationsTab.setObjectName(_fromUtf8("specialDesignationsTab"))
        self.gridLayout_16 = QtGui.QGridLayout(self.specialDesignationsTab)
        self.gridLayout_16.setObjectName(_fromUtf8("gridLayout_16"))
        self.specDesTableView = QtGui.QTableView(self.specialDesignationsTab)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("MS Shell Dlg 2"))
        font.setPointSize(8)
        self.specDesTableView.setFont(font)
        self.specDesTableView.setStyleSheet(_fromUtf8("border-width:0.5px;\n"
"border-style: solid;\n"
"border-radius: 2px;\n"
"border-color:  rgb(100,100,100);\n"
"background-color: rgb(213, 234, 234);"))
        self.specDesTableView.setEditTriggers(QtGui.QAbstractItemView.NoEditTriggers)
        self.specDesTableView.setAlternatingRowColors(False)
        self.specDesTableView.setSelectionMode(QtGui.QAbstractItemView.SingleSelection)
        self.specDesTableView.setSelectionBehavior(QtGui.QAbstractItemView.SelectRows)
        self.specDesTableView.setObjectName(_fromUtf8("specDesTableView"))
        self.specDesTableView.horizontalHeader().setStretchLastSection(True)
        self.specDesTableView.verticalHeader().setVisible(False)
        self.gridLayout_16.addWidget(self.specDesTableView, 0, 0, 1, 1)
        self.srwrTabWidget.addTab(self.specialDesignationsTab, _fromUtf8(""))
        self.reinstatementCatsTab = QtGui.QWidget()
        self.reinstatementCatsTab.setObjectName(_fromUtf8("reinstatementCatsTab"))
        self.gridLayout_17 = QtGui.QGridLayout(self.reinstatementCatsTab)
        self.gridLayout_17.setObjectName(_fromUtf8("gridLayout_17"))
        self.reinstCatTableView = QtGui.QTableView(self.reinstatementCatsTab)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("MS Shell Dlg 2"))
        font.setPointSize(8)
        self.reinstCatTableView.setFont(font)
        self.reinstCatTableView.setStyleSheet(_fromUtf8("border-width:0.5px;\n"
"border-style: solid;\n"
"border-radius: 2px;\n"
"border-color:  rgb(100,100,100);\n"
"background-color: rgb(213, 234, 234);"))
        self.reinstCatTableView.setEditTriggers(QtGui.QAbstractItemView.NoEditTriggers)
        self.reinstCatTableView.setAlternatingRowColors(False)
        self.reinstCatTableView.setSelectionMode(QtGui.QAbstractItemView.SingleSelection)
        self.reinstCatTableView.setSelectionBehavior(QtGui.QAbstractItemView.SelectRows)
        self.reinstCatTableView.setObjectName(_fromUtf8("reinstCatTableView"))
        self.reinstCatTableView.horizontalHeader().setStretchLastSection(True)
        self.reinstCatTableView.verticalHeader().setVisible(False)
        self.gridLayout_17.addWidget(self.reinstCatTableView, 0, 0, 1, 1)
        self.srwrTabWidget.addTab(self.reinstatementCatsTab, _fromUtf8(""))
        self.gridLayout_33.addWidget(self.srwrTabWidget, 0, 0, 1, 1)
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.groupBox_2 = QtGui.QGroupBox(self.srwrRecordsGroupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_2.sizePolicy().hasHeightForWidth())
        self.groupBox_2.setSizePolicy(sizePolicy)
        self.groupBox_2.setObjectName(_fromUtf8("groupBox_2"))
        self.gridLayout_14 = QtGui.QGridLayout(self.groupBox_2)
        self.gridLayout_14.setObjectName(_fromUtf8("gridLayout_14"))
        self.srwrAddPushButton = QtGui.QPushButton(self.groupBox_2)
        self.srwrAddPushButton.setMaximumSize(QtCore.QSize(100, 16777215))
        self.srwrAddPushButton.setObjectName(_fromUtf8("srwrAddPushButton"))
        self.gridLayout_14.addWidget(self.srwrAddPushButton, 0, 0, 1, 1)
        self.srwrModifyPushButton = QtGui.QPushButton(self.groupBox_2)
        self.srwrModifyPushButton.setMaximumSize(QtCore.QSize(100, 16777215))
        self.srwrModifyPushButton.setObjectName(_fromUtf8("srwrModifyPushButton"))
        self.gridLayout_14.addWidget(self.srwrModifyPushButton, 0, 1, 1, 1)
        self.srwrDeletePushButton = QtGui.QPushButton(self.groupBox_2)
        self.srwrDeletePushButton.setMaximumSize(QtCore.QSize(100, 16777215))
        self.srwrDeletePushButton.setObjectName(_fromUtf8("srwrDeletePushButton"))
        self.gridLayout_14.addWidget(self.srwrDeletePushButton, 0, 2, 1, 1)
        self.srwrViewPushButton = QtGui.QPushButton(self.groupBox_2)
        self.srwrViewPushButton.setMaximumSize(QtCore.QSize(100, 16777215))
        self.srwrViewPushButton.setObjectName(_fromUtf8("srwrViewPushButton"))
        self.gridLayout_14.addWidget(self.srwrViewPushButton, 0, 3, 1, 1)
        self.horizontalLayout_2.addWidget(self.groupBox_2)
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem)
        self.srwrExtentPushButton = QtGui.QPushButton(self.srwrRecordsGroupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.srwrExtentPushButton.sizePolicy().hasHeightForWidth())
        self.srwrExtentPushButton.setSizePolicy(sizePolicy)
        self.srwrExtentPushButton.setMaximumSize(QtCore.QSize(100, 16777215))
        self.srwrExtentPushButton.setObjectName(_fromUtf8("srwrExtentPushButton"))
        self.horizontalLayout_2.addWidget(self.srwrExtentPushButton)
        self.gridLayout_33.addLayout(self.horizontalLayout_2, 1, 0, 1, 1)
        self.gridLayout_34.addWidget(self.srwrRecordsGroupBox, 1, 0, 1, 1)
        self.groupBox_3 = QtGui.QGroupBox(self.scrollAreaWidgetContents)
        self.groupBox_3.setMinimumSize(QtCore.QSize(1141, 630))
        self.groupBox_3.setObjectName(_fromUtf8("groupBox_3"))
        self.gridLayout_12 = QtGui.QGridLayout(self.groupBox_3)
        self.gridLayout_12.setContentsMargins(-1, 5, -1, -1)
        self.gridLayout_12.setObjectName(_fromUtf8("gridLayout_12"))
        self.horizontalLayout_24 = QtGui.QHBoxLayout()
        self.horizontalLayout_24.setContentsMargins(-1, 30, -1, -1)
        self.horizontalLayout_24.setObjectName(_fromUtf8("horizontalLayout_24"))
        spacerItem1 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_24.addItem(spacerItem1)
        self.srwrPushButton = QtGui.QPushButton(self.groupBox_3)
        self.srwrPushButton.setMaximumSize(QtCore.QSize(130, 16777215))
        self.srwrPushButton.setObjectName(_fromUtf8("srwrPushButton"))
        self.horizontalLayout_24.addWidget(self.srwrPushButton)
        self.gridLayout_12.addLayout(self.horizontalLayout_24, 5, 1, 1, 1)
        self.operationsGroupBox = QtGui.QGroupBox(self.groupBox_3)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.operationsGroupBox.sizePolicy().hasHeightForWidth())
        self.operationsGroupBox.setSizePolicy(sizePolicy)
        self.operationsGroupBox.setMinimumSize(QtCore.QSize(421, 56))
        self.operationsGroupBox.setObjectName(_fromUtf8("operationsGroupBox"))
        self.gridLayout_3 = QtGui.QGridLayout(self.operationsGroupBox)
        self.gridLayout_3.setObjectName(_fromUtf8("gridLayout_3"))
        self.addPushButton = QtGui.QPushButton(self.operationsGroupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.addPushButton.sizePolicy().hasHeightForWidth())
        self.addPushButton.setSizePolicy(sizePolicy)
        self.addPushButton.setMaximumSize(QtCore.QSize(120, 16777215))
        self.addPushButton.setObjectName(_fromUtf8("addPushButton"))
        self.gridLayout_3.addWidget(self.addPushButton, 0, 0, 1, 1)
        self.modifyPushButton = QtGui.QPushButton(self.operationsGroupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.modifyPushButton.sizePolicy().hasHeightForWidth())
        self.modifyPushButton.setSizePolicy(sizePolicy)
        self.modifyPushButton.setMaximumSize(QtCore.QSize(120, 16777215))
        self.modifyPushButton.setObjectName(_fromUtf8("modifyPushButton"))
        self.gridLayout_3.addWidget(self.modifyPushButton, 0, 1, 1, 1)
        self.closeOpPushButton = QtGui.QPushButton(self.operationsGroupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.closeOpPushButton.sizePolicy().hasHeightForWidth())
        self.closeOpPushButton.setSizePolicy(sizePolicy)
        self.closeOpPushButton.setMaximumSize(QtCore.QSize(120, 16777215))
        self.closeOpPushButton.setObjectName(_fromUtf8("closeOpPushButton"))
        self.gridLayout_3.addWidget(self.closeOpPushButton, 0, 2, 1, 1)
        self.filterPushButton = QtGui.QPushButton(self.operationsGroupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.filterPushButton.sizePolicy().hasHeightForWidth())
        self.filterPushButton.setSizePolicy(sizePolicy)
        self.filterPushButton.setMaximumSize(QtCore.QSize(120, 16777215))
        self.filterPushButton.setObjectName(_fromUtf8("filterPushButton"))
        self.gridLayout_3.addWidget(self.filterPushButton, 0, 3, 1, 1)
        self.mapPushButton = QtGui.QPushButton(self.operationsGroupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.mapPushButton.sizePolicy().hasHeightForWidth())
        self.mapPushButton.setSizePolicy(sizePolicy)
        self.mapPushButton.setMaximumSize(QtCore.QSize(120, 16777215))
        self.mapPushButton.setObjectName(_fromUtf8("mapPushButton"))
        self.gridLayout_3.addWidget(self.mapPushButton, 0, 4, 1, 1)
        self.gridLayout_12.addWidget(self.operationsGroupBox, 0, 1, 1, 1)
        self.LsgRecordGroupBox = QtGui.QGroupBox(self.groupBox_3)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.LsgRecordGroupBox.sizePolicy().hasHeightForWidth())
        self.LsgRecordGroupBox.setSizePolicy(sizePolicy)
        self.LsgRecordGroupBox.setMinimumSize(QtCore.QSize(401, 311))
        self.LsgRecordGroupBox.setMaximumSize(QtCore.QSize(16777215, 351))
        self.LsgRecordGroupBox.setSizeIncrement(QtCore.QSize(0, 0))
        self.LsgRecordGroupBox.setBaseSize(QtCore.QSize(0, 0))
        self.LsgRecordGroupBox.setObjectName(_fromUtf8("LsgRecordGroupBox"))
        self.gridLayout_28 = QtGui.QGridLayout(self.LsgRecordGroupBox)
        self.gridLayout_28.setObjectName(_fromUtf8("gridLayout_28"))
        self.horizontalLayout_6 = QtGui.QHBoxLayout()
        self.horizontalLayout_6.setSpacing(0)
        self.horizontalLayout_6.setSizeConstraint(QtGui.QLayout.SetNoConstraint)
        self.horizontalLayout_6.setObjectName(_fromUtf8("horizontalLayout_6"))
        self.descriptionLabel = QtGui.QLabel(self.LsgRecordGroupBox)
        self.descriptionLabel.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.descriptionLabel.setObjectName(_fromUtf8("descriptionLabel"))
        self.horizontalLayout_6.addWidget(self.descriptionLabel)
        spacerItem2 = QtGui.QSpacerItem(8, 20, QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem2)
        self.descriptionTextEdit = QtGui.QTextEdit(self.LsgRecordGroupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.descriptionTextEdit.sizePolicy().hasHeightForWidth())
        self.descriptionTextEdit.setSizePolicy(sizePolicy)
        self.descriptionTextEdit.setMinimumSize(QtCore.QSize(0, 40))
        self.descriptionTextEdit.setMaximumSize(QtCore.QSize(16777215, 50))
        self.descriptionTextEdit.setStyleSheet(_fromUtf8("border-width:0.5px;\n"
"border-style: solid;\n"
"border-radius: 2px;\n"
"border-color:  rgb(100,100,100);\n"
"background-color: rgb(213, 234, 234);"))
        self.descriptionTextEdit.setReadOnly(True)
        self.descriptionTextEdit.setObjectName(_fromUtf8("descriptionTextEdit"))
        self.horizontalLayout_6.addWidget(self.descriptionTextEdit)
        self.gridLayout_28.addLayout(self.horizontalLayout_6, 2, 0, 1, 1)
        self.horizontalLayout_7 = QtGui.QHBoxLayout()
        self.horizontalLayout_7.setSpacing(0)
        self.horizontalLayout_7.setObjectName(_fromUtf8("horizontalLayout_7"))
        self.localityLabel = QtGui.QLabel(self.LsgRecordGroupBox)
        self.localityLabel.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.localityLabel.setObjectName(_fromUtf8("localityLabel"))
        self.horizontalLayout_7.addWidget(self.localityLabel)
        self.localityStackedWidget = QtGui.QStackedWidget(self.LsgRecordGroupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.localityStackedWidget.sizePolicy().hasHeightForWidth())
        self.localityStackedWidget.setSizePolicy(sizePolicy)
        self.localityStackedWidget.setMinimumSize(QtCore.QSize(290, 20))
        self.localityStackedWidget.setObjectName(_fromUtf8("localityStackedWidget"))
        self.localityReadOnlyPage = QtGui.QWidget()
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.localityReadOnlyPage.sizePolicy().hasHeightForWidth())
        self.localityReadOnlyPage.setSizePolicy(sizePolicy)
        self.localityReadOnlyPage.setMinimumSize(QtCore.QSize(290, 20))
        self.localityReadOnlyPage.setObjectName(_fromUtf8("localityReadOnlyPage"))
        self.gridLayout_6 = QtGui.QGridLayout(self.localityReadOnlyPage)
        self.gridLayout_6.setSpacing(0)
        self.gridLayout_6.setContentsMargins(27, 0, 0, 0)
        self.gridLayout_6.setObjectName(_fromUtf8("gridLayout_6"))
        self.localityLineEdit = QtGui.QLineEdit(self.localityReadOnlyPage)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.localityLineEdit.sizePolicy().hasHeightForWidth())
        self.localityLineEdit.setSizePolicy(sizePolicy)
        self.localityLineEdit.setMinimumSize(QtCore.QSize(278, 20))
        self.localityLineEdit.setMaximumSize(QtCore.QSize(16777215, 20))
        self.localityLineEdit.setStyleSheet(_fromUtf8("border-width:0.5px;\n"
"border-style: solid;\n"
"border-radius: 2px;\n"
"border-color:  rgb(100,100,100);\n"
"background-color: rgb(213, 234, 234);"))
        self.localityLineEdit.setReadOnly(True)
        self.localityLineEdit.setObjectName(_fromUtf8("localityLineEdit"))
        self.gridLayout_6.addWidget(self.localityLineEdit, 0, 0, 1, 1)
        self.localityStackedWidget.addWidget(self.localityReadOnlyPage)
        self.localityModifyPage = QtGui.QWidget()
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.localityModifyPage.sizePolicy().hasHeightForWidth())
        self.localityModifyPage.setSizePolicy(sizePolicy)
        self.localityModifyPage.setMinimumSize(QtCore.QSize(290, 20))
        self.localityModifyPage.setObjectName(_fromUtf8("localityModifyPage"))
        self.gridLayout_8 = QtGui.QGridLayout(self.localityModifyPage)
        self.gridLayout_8.setSpacing(0)
        self.gridLayout_8.setContentsMargins(27, 0, 0, 0)
        self.gridLayout_8.setObjectName(_fromUtf8("gridLayout_8"))
        self.localityComboBox = QtGui.QComboBox(self.localityModifyPage)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.localityComboBox.sizePolicy().hasHeightForWidth())
        self.localityComboBox.setSizePolicy(sizePolicy)
        self.localityComboBox.setMinimumSize(QtCore.QSize(278, 20))
        self.localityComboBox.setMaximumSize(QtCore.QSize(16777215, 20))
        self.localityComboBox.setObjectName(_fromUtf8("localityComboBox"))
        self.gridLayout_8.addWidget(self.localityComboBox, 0, 0, 1, 1)
        self.localityStackedWidget.addWidget(self.localityModifyPage)
        self.horizontalLayout_7.addWidget(self.localityStackedWidget)
        self.gridLayout_28.addLayout(self.horizontalLayout_7, 3, 0, 1, 1)
        self.horizontalLayout_8 = QtGui.QHBoxLayout()
        self.horizontalLayout_8.setSpacing(0)
        self.horizontalLayout_8.setObjectName(_fromUtf8("horizontalLayout_8"))
        self.townLabel = QtGui.QLabel(self.LsgRecordGroupBox)
        self.townLabel.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.townLabel.setObjectName(_fromUtf8("townLabel"))
        self.horizontalLayout_8.addWidget(self.townLabel)
        self.townStackedWidget = QtGui.QStackedWidget(self.LsgRecordGroupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.townStackedWidget.sizePolicy().hasHeightForWidth())
        self.townStackedWidget.setSizePolicy(sizePolicy)
        self.townStackedWidget.setMinimumSize(QtCore.QSize(290, 20))
        self.townStackedWidget.setObjectName(_fromUtf8("townStackedWidget"))
        self.townReadOnlyPage = QtGui.QWidget()
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.townReadOnlyPage.sizePolicy().hasHeightForWidth())
        self.townReadOnlyPage.setSizePolicy(sizePolicy)
        self.townReadOnlyPage.setMinimumSize(QtCore.QSize(290, 20))
        self.townReadOnlyPage.setObjectName(_fromUtf8("townReadOnlyPage"))
        self.gridLayout_9 = QtGui.QGridLayout(self.townReadOnlyPage)
        self.gridLayout_9.setSpacing(0)
        self.gridLayout_9.setContentsMargins(31, 0, 0, 0)
        self.gridLayout_9.setObjectName(_fromUtf8("gridLayout_9"))
        self.townLineEdit = QtGui.QLineEdit(self.townReadOnlyPage)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.townLineEdit.sizePolicy().hasHeightForWidth())
        self.townLineEdit.setSizePolicy(sizePolicy)
        self.townLineEdit.setMinimumSize(QtCore.QSize(278, 20))
        self.townLineEdit.setMaximumSize(QtCore.QSize(16777215, 20))
        self.townLineEdit.setStyleSheet(_fromUtf8("border-width:0.5px;\n"
"border-style: solid;\n"
"border-radius: 2px;\n"
"border-color:  rgb(100,100,100);\n"
"background-color: rgb(213, 234, 234);"))
        self.townLineEdit.setReadOnly(True)
        self.townLineEdit.setObjectName(_fromUtf8("townLineEdit"))
        self.gridLayout_9.addWidget(self.townLineEdit, 0, 1, 1, 1)
        spacerItem3 = QtGui.QSpacerItem(6, 20, QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Minimum)
        self.gridLayout_9.addItem(spacerItem3, 0, 0, 1, 1)
        self.townStackedWidget.addWidget(self.townReadOnlyPage)
        self.townModifyPage = QtGui.QWidget()
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.townModifyPage.sizePolicy().hasHeightForWidth())
        self.townModifyPage.setSizePolicy(sizePolicy)
        self.townModifyPage.setMinimumSize(QtCore.QSize(290, 20))
        self.townModifyPage.setObjectName(_fromUtf8("townModifyPage"))
        self.gridLayout_10 = QtGui.QGridLayout(self.townModifyPage)
        self.gridLayout_10.setSpacing(0)
        self.gridLayout_10.setContentsMargins(31, 0, 0, 0)
        self.gridLayout_10.setObjectName(_fromUtf8("gridLayout_10"))
        self.townComboBox = QtGui.QComboBox(self.townModifyPage)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.townComboBox.sizePolicy().hasHeightForWidth())
        self.townComboBox.setSizePolicy(sizePolicy)
        self.townComboBox.setMinimumSize(QtCore.QSize(278, 20))
        self.townComboBox.setMaximumSize(QtCore.QSize(16777215, 20))
        self.townComboBox.setObjectName(_fromUtf8("townComboBox"))
        self.gridLayout_10.addWidget(self.townComboBox, 0, 1, 1, 1)
        spacerItem4 = QtGui.QSpacerItem(6, 20, QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Minimum)
        self.gridLayout_10.addItem(spacerItem4, 0, 0, 1, 1)
        self.townStackedWidget.addWidget(self.townModifyPage)
        self.horizontalLayout_8.addWidget(self.townStackedWidget)
        self.gridLayout_28.addLayout(self.horizontalLayout_8, 4, 0, 1, 1)
        self.horizontalLayout_5 = QtGui.QHBoxLayout()
        self.horizontalLayout_5.setSpacing(0)
        self.horizontalLayout_5.setObjectName(_fromUtf8("horizontalLayout_5"))
        self.typeLabel = QtGui.QLabel(self.LsgRecordGroupBox)
        self.typeLabel.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.typeLabel.setObjectName(_fromUtf8("typeLabel"))
        self.horizontalLayout_5.addWidget(self.typeLabel)
        spacerItem5 = QtGui.QSpacerItem(7, 20, QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem5)
        self.typeStackedWidget = QtGui.QStackedWidget(self.LsgRecordGroupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.typeStackedWidget.sizePolicy().hasHeightForWidth())
        self.typeStackedWidget.setSizePolicy(sizePolicy)
        self.typeStackedWidget.setMinimumSize(QtCore.QSize(278, 20))
        self.typeStackedWidget.setObjectName(_fromUtf8("typeStackedWidget"))
        self.typeReadOnlyPage = QtGui.QWidget()
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.typeReadOnlyPage.sizePolicy().hasHeightForWidth())
        self.typeReadOnlyPage.setSizePolicy(sizePolicy)
        self.typeReadOnlyPage.setMinimumSize(QtCore.QSize(290, 20))
        self.typeReadOnlyPage.setObjectName(_fromUtf8("typeReadOnlyPage"))
        self.gridLayout_5 = QtGui.QGridLayout(self.typeReadOnlyPage)
        self.gridLayout_5.setSpacing(0)
        self.gridLayout_5.setContentsMargins(32, 0, 0, 0)
        self.gridLayout_5.setObjectName(_fromUtf8("gridLayout_5"))
        self.typeLineEdit = QtGui.QLineEdit(self.typeReadOnlyPage)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.typeLineEdit.sizePolicy().hasHeightForWidth())
        self.typeLineEdit.setSizePolicy(sizePolicy)
        self.typeLineEdit.setMinimumSize(QtCore.QSize(278, 20))
        self.typeLineEdit.setMaximumSize(QtCore.QSize(99999, 20))
        self.typeLineEdit.setStyleSheet(_fromUtf8("border-width:0.5px;\n"
"border-style: solid;\n"
"border-radius: 2px;\n"
"border-color:  rgb(100,100,100);\n"
"background-color: rgb(213, 234, 234);"))
        self.typeLineEdit.setReadOnly(True)
        self.typeLineEdit.setObjectName(_fromUtf8("typeLineEdit"))
        self.gridLayout_5.addWidget(self.typeLineEdit, 0, 0, 1, 1)
        self.typeStackedWidget.addWidget(self.typeReadOnlyPage)
        self.typeModifyPage = QtGui.QWidget()
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.typeModifyPage.sizePolicy().hasHeightForWidth())
        self.typeModifyPage.setSizePolicy(sizePolicy)
        self.typeModifyPage.setMinimumSize(QtCore.QSize(290, 20))
        self.typeModifyPage.setObjectName(_fromUtf8("typeModifyPage"))
        self.gridLayout_4 = QtGui.QGridLayout(self.typeModifyPage)
        self.gridLayout_4.setSpacing(0)
        self.gridLayout_4.setContentsMargins(32, 0, 0, 0)
        self.gridLayout_4.setObjectName(_fromUtf8("gridLayout_4"))
        self.recordTypeComboBox = QtGui.QComboBox(self.typeModifyPage)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.recordTypeComboBox.sizePolicy().hasHeightForWidth())
        self.recordTypeComboBox.setSizePolicy(sizePolicy)
        self.recordTypeComboBox.setMinimumSize(QtCore.QSize(278, 20))
        self.recordTypeComboBox.setMaximumSize(QtCore.QSize(16777215, 20))
        self.recordTypeComboBox.setObjectName(_fromUtf8("recordTypeComboBox"))
        self.gridLayout_4.addWidget(self.recordTypeComboBox, 0, 0, 1, 1)
        self.typeStackedWidget.addWidget(self.typeModifyPage)
        self.horizontalLayout_5.addWidget(self.typeStackedWidget)
        self.gridLayout_28.addLayout(self.horizontalLayout_5, 1, 0, 1, 1)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.startDateLabel = QtGui.QLabel(self.LsgRecordGroupBox)
        self.startDateLabel.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.startDateLabel.setObjectName(_fromUtf8("startDateLabel"))
        self.horizontalLayout.addWidget(self.startDateLabel)
        spacerItem6 = QtGui.QSpacerItem(13, 20, QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem6)
        self.startDateStackedWidget = QtGui.QStackedWidget(self.LsgRecordGroupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.startDateStackedWidget.sizePolicy().hasHeightForWidth())
        self.startDateStackedWidget.setSizePolicy(sizePolicy)
        self.startDateStackedWidget.setMinimumSize(QtCore.QSize(126, 20))
        self.startDateStackedWidget.setMaximumSize(QtCore.QSize(126, 20))
        self.startDateStackedWidget.setObjectName(_fromUtf8("startDateStackedWidget"))
        self.startDateReadOnlyPage = QtGui.QWidget()
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.startDateReadOnlyPage.sizePolicy().hasHeightForWidth())
        self.startDateReadOnlyPage.setSizePolicy(sizePolicy)
        self.startDateReadOnlyPage.setMinimumSize(QtCore.QSize(80, 20))
        self.startDateReadOnlyPage.setObjectName(_fromUtf8("startDateReadOnlyPage"))
        self.gridLayout = QtGui.QGridLayout(self.startDateReadOnlyPage)
        self.gridLayout.setSpacing(0)
        self.gridLayout.setMargin(0)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.startDateLineEdit = QtGui.QLineEdit(self.startDateReadOnlyPage)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.startDateLineEdit.sizePolicy().hasHeightForWidth())
        self.startDateLineEdit.setSizePolicy(sizePolicy)
        self.startDateLineEdit.setMinimumSize(QtCore.QSize(126, 20))
        self.startDateLineEdit.setMaximumSize(QtCore.QSize(126, 20))
        self.startDateLineEdit.setStyleSheet(_fromUtf8("border-width:0.5px;\n"
"border-style: solid;\n"
"border-radius: 2px;\n"
"border-color:  rgb(100,100,100);\n"
"background-color: rgb(213, 234, 234);"))
        self.startDateLineEdit.setReadOnly(True)
        self.startDateLineEdit.setObjectName(_fromUtf8("startDateLineEdit"))
        self.gridLayout.addWidget(self.startDateLineEdit, 0, 0, 1, 1)
        self.startDateStackedWidget.addWidget(self.startDateReadOnlyPage)
        self.startDateModifyPage = QtGui.QWidget()
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.startDateModifyPage.sizePolicy().hasHeightForWidth())
        self.startDateModifyPage.setSizePolicy(sizePolicy)
        self.startDateModifyPage.setMinimumSize(QtCore.QSize(80, 20))
        self.startDateModifyPage.setObjectName(_fromUtf8("startDateModifyPage"))
        self.gridLayout_27 = QtGui.QGridLayout(self.startDateModifyPage)
        self.gridLayout_27.setSpacing(0)
        self.gridLayout_27.setMargin(0)
        self.gridLayout_27.setObjectName(_fromUtf8("gridLayout_27"))
        self.startDateDateEdit = QtGui.QDateEdit(self.startDateModifyPage)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.startDateDateEdit.sizePolicy().hasHeightForWidth())
        self.startDateDateEdit.setSizePolicy(sizePolicy)
        self.startDateDateEdit.setMinimumSize(QtCore.QSize(126, 20))
        self.startDateDateEdit.setMaximumSize(QtCore.QSize(16777215, 20))
        self.startDateDateEdit.setCalendarPopup(True)
        self.startDateDateEdit.setObjectName(_fromUtf8("startDateDateEdit"))
        self.gridLayout_27.addWidget(self.startDateDateEdit, 0, 0, 1, 1)
        self.startDateStackedWidget.addWidget(self.startDateModifyPage)
        self.horizontalLayout.addWidget(self.startDateStackedWidget)
        spacerItem7 = QtGui.QSpacerItem(20, 20, QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem7)
        self.entryDateLabel = QtGui.QLabel(self.LsgRecordGroupBox)
        self.entryDateLabel.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.entryDateLabel.setObjectName(_fromUtf8("entryDateLabel"))
        self.horizontalLayout.addWidget(self.entryDateLabel)
        spacerItem8 = QtGui.QSpacerItem(10, 20, QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem8)
        self.entryDateLineEdit = QtGui.QLineEdit(self.LsgRecordGroupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.entryDateLineEdit.sizePolicy().hasHeightForWidth())
        self.entryDateLineEdit.setSizePolicy(sizePolicy)
        self.entryDateLineEdit.setMinimumSize(QtCore.QSize(126, 20))
        self.entryDateLineEdit.setMaximumSize(QtCore.QSize(126, 20))
        self.entryDateLineEdit.setStyleSheet(_fromUtf8("border-width:0.5px;\n"
"border-style: solid;\n"
"border-radius: 2px;\n"
"border-color:  rgb(100,100,100);\n"
"background-color: rgb(213, 234, 234);"))
        self.entryDateLineEdit.setReadOnly(True)
        self.entryDateLineEdit.setObjectName(_fromUtf8("entryDateLineEdit"))
        self.horizontalLayout.addWidget(self.entryDateLineEdit)
        spacerItem9 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem9)
        self.gridLayout_28.addLayout(self.horizontalLayout, 8, 0, 1, 1)
        self.horizontalLayout_12 = QtGui.QHBoxLayout()
        self.horizontalLayout_12.setSpacing(0)
        self.horizontalLayout_12.setObjectName(_fromUtf8("horizontalLayout_12"))
        self.lastUpdateLabel = QtGui.QLabel(self.LsgRecordGroupBox)
        self.lastUpdateLabel.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lastUpdateLabel.setObjectName(_fromUtf8("lastUpdateLabel"))
        self.horizontalLayout_12.addWidget(self.lastUpdateLabel)
        spacerItem10 = QtGui.QSpacerItem(5, 20, QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_12.addItem(spacerItem10)
        self.updateDateLineEdit = QtGui.QLineEdit(self.LsgRecordGroupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.updateDateLineEdit.sizePolicy().hasHeightForWidth())
        self.updateDateLineEdit.setSizePolicy(sizePolicy)
        self.updateDateLineEdit.setMinimumSize(QtCore.QSize(126, 20))
        self.updateDateLineEdit.setMaximumSize(QtCore.QSize(126, 20))
        self.updateDateLineEdit.setStyleSheet(_fromUtf8("border-width:0.5px;\n"
"border-style: solid;\n"
"border-radius: 2px;\n"
"border-color:  rgb(100,100,100);\n"
"background-color: rgb(213, 234, 234);"))
        self.updateDateLineEdit.setObjectName(_fromUtf8("updateDateLineEdit"))
        self.horizontalLayout_12.addWidget(self.updateDateLineEdit)
        spacerItem11 = QtGui.QSpacerItem(60, 20, QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_12.addItem(spacerItem11)
        self.byLabel = QtGui.QLabel(self.LsgRecordGroupBox)
        self.byLabel.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.byLabel.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.byLabel.setObjectName(_fromUtf8("byLabel"))
        self.horizontalLayout_12.addWidget(self.byLabel)
        spacerItem12 = QtGui.QSpacerItem(10, 20, QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_12.addItem(spacerItem12)
        self.byLineEdit = QtGui.QLineEdit(self.LsgRecordGroupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.byLineEdit.sizePolicy().hasHeightForWidth())
        self.byLineEdit.setSizePolicy(sizePolicy)
        self.byLineEdit.setMinimumSize(QtCore.QSize(106, 20))
        self.byLineEdit.setMaximumSize(QtCore.QSize(16777215, 20))
        self.byLineEdit.setStyleSheet(_fromUtf8("border-width:0.5px;\n"
"border-style: solid;\n"
"border-radius: 2px;\n"
"border-color:  rgb(100,100,100);\n"
"background-color: rgb(213, 234, 234);"))
        self.byLineEdit.setReadOnly(True)
        self.byLineEdit.setObjectName(_fromUtf8("byLineEdit"))
        self.horizontalLayout_12.addWidget(self.byLineEdit)
        self.gridLayout_28.addLayout(self.horizontalLayout_12, 7, 0, 1, 1)
        self.horizontalLayout_9 = QtGui.QHBoxLayout()
        self.horizontalLayout_9.setSpacing(0)
        self.horizontalLayout_9.setObjectName(_fromUtf8("horizontalLayout_9"))
        self.countyLabel = QtGui.QLabel(self.LsgRecordGroupBox)
        self.countyLabel.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.countyLabel.setObjectName(_fromUtf8("countyLabel"))
        self.horizontalLayout_9.addWidget(self.countyLabel)
        self.countyStackedWidget = QtGui.QStackedWidget(self.LsgRecordGroupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.countyStackedWidget.sizePolicy().hasHeightForWidth())
        self.countyStackedWidget.setSizePolicy(sizePolicy)
        self.countyStackedWidget.setMinimumSize(QtCore.QSize(290, 20))
        self.countyStackedWidget.setObjectName(_fromUtf8("countyStackedWidget"))
        self.countyReadOnlyPage = QtGui.QWidget()
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.countyReadOnlyPage.sizePolicy().hasHeightForWidth())
        self.countyReadOnlyPage.setSizePolicy(sizePolicy)
        self.countyReadOnlyPage.setMinimumSize(QtCore.QSize(290, 20))
        self.countyReadOnlyPage.setObjectName(_fromUtf8("countyReadOnlyPage"))
        self.gridLayout_11 = QtGui.QGridLayout(self.countyReadOnlyPage)
        self.gridLayout_11.setSpacing(0)
        self.gridLayout_11.setContentsMargins(22, 0, 0, 0)
        self.gridLayout_11.setObjectName(_fromUtf8("gridLayout_11"))
        self.countyLineEdit = QtGui.QLineEdit(self.countyReadOnlyPage)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.countyLineEdit.sizePolicy().hasHeightForWidth())
        self.countyLineEdit.setSizePolicy(sizePolicy)
        self.countyLineEdit.setMinimumSize(QtCore.QSize(278, 20))
        self.countyLineEdit.setMaximumSize(QtCore.QSize(16777215, 20))
        self.countyLineEdit.setStyleSheet(_fromUtf8("border-width:0.5px;\n"
"border-style: solid;\n"
"border-radius: 2px;\n"
"border-color:  rgb(100,100,100);\n"
"background-color: rgb(213, 234, 234);"))
        self.countyLineEdit.setReadOnly(True)
        self.countyLineEdit.setObjectName(_fromUtf8("countyLineEdit"))
        self.gridLayout_11.addWidget(self.countyLineEdit, 0, 1, 1, 1)
        spacerItem13 = QtGui.QSpacerItem(6, 20, QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Minimum)
        self.gridLayout_11.addItem(spacerItem13, 0, 0, 1, 1)
        self.countyStackedWidget.addWidget(self.countyReadOnlyPage)
        self.countyModifyPage = QtGui.QWidget()
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.countyModifyPage.sizePolicy().hasHeightForWidth())
        self.countyModifyPage.setSizePolicy(sizePolicy)
        self.countyModifyPage.setMinimumSize(QtCore.QSize(290, 20))
        self.countyModifyPage.setObjectName(_fromUtf8("countyModifyPage"))
        self.gridLayout_18 = QtGui.QGridLayout(self.countyModifyPage)
        self.gridLayout_18.setSpacing(0)
        self.gridLayout_18.setContentsMargins(22, 0, 0, 0)
        self.gridLayout_18.setObjectName(_fromUtf8("gridLayout_18"))
        self.countyComboBox = QtGui.QComboBox(self.countyModifyPage)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.countyComboBox.sizePolicy().hasHeightForWidth())
        self.countyComboBox.setSizePolicy(sizePolicy)
        self.countyComboBox.setMinimumSize(QtCore.QSize(278, 20))
        self.countyComboBox.setMaximumSize(QtCore.QSize(16777215, 20))
        self.countyComboBox.setObjectName(_fromUtf8("countyComboBox"))
        self.gridLayout_18.addWidget(self.countyComboBox, 0, 1, 1, 1)
        spacerItem14 = QtGui.QSpacerItem(6, 20, QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Minimum)
        self.gridLayout_18.addItem(spacerItem14, 0, 0, 1, 1)
        self.countyStackedWidget.addWidget(self.countyModifyPage)
        self.horizontalLayout_9.addWidget(self.countyStackedWidget)
        self.gridLayout_28.addLayout(self.horizontalLayout_9, 5, 0, 1, 1)
        self.horizontalLayout_4 = QtGui.QHBoxLayout()
        self.horizontalLayout_4.setSpacing(6)
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        self.usrnLabel_2 = QtGui.QLabel(self.LsgRecordGroupBox)
        self.usrnLabel_2.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.usrnLabel_2.setObjectName(_fromUtf8("usrnLabel_2"))
        self.horizontalLayout_4.addWidget(self.usrnLabel_2)
        spacerItem15 = QtGui.QSpacerItem(30, 20, QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem15)
        self.usrnLineEdit = QtGui.QLineEdit(self.LsgRecordGroupBox)
        self.usrnLineEdit.setEnabled(True)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.usrnLineEdit.sizePolicy().hasHeightForWidth())
        self.usrnLineEdit.setSizePolicy(sizePolicy)
        self.usrnLineEdit.setMinimumSize(QtCore.QSize(126, 20))
        self.usrnLineEdit.setMaximumSize(QtCore.QSize(126, 20))
        self.usrnLineEdit.setStyleSheet(_fromUtf8("border-width:0.5px;\n"
"border-style: solid;\n"
"border-radius: 2px;\n"
"border-color:  rgb(100,100,100);\n"
"background-color: rgb(213, 234, 234);"))
        self.usrnLineEdit.setReadOnly(True)
        self.usrnLineEdit.setObjectName(_fromUtf8("usrnLineEdit"))
        self.horizontalLayout_4.addWidget(self.usrnLineEdit)
        spacerItem16 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem16)
        self.versionLabel = QtGui.QLabel(self.LsgRecordGroupBox)
        self.versionLabel.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.versionLabel.setObjectName(_fromUtf8("versionLabel"))
        self.horizontalLayout_4.addWidget(self.versionLabel)
        self.versionLineEdit = QtGui.QLineEdit(self.LsgRecordGroupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.versionLineEdit.sizePolicy().hasHeightForWidth())
        self.versionLineEdit.setSizePolicy(sizePolicy)
        self.versionLineEdit.setMinimumSize(QtCore.QSize(0, 20))
        self.versionLineEdit.setMaximumSize(QtCore.QSize(40, 20))
        self.versionLineEdit.setStyleSheet(_fromUtf8("border-width:0.5px;\n"
"border-style: solid;\n"
"border-radius: 2px;\n"
"border-color:  rgb(100,100,100);\n"
"background-color: rgb(213, 234, 234);"))
        self.versionLineEdit.setReadOnly(True)
        self.versionLineEdit.setObjectName(_fromUtf8("versionLineEdit"))
        self.horizontalLayout_4.addWidget(self.versionLineEdit)
        self.gridLayout_28.addLayout(self.horizontalLayout_4, 0, 0, 1, 1)
        self.horizontalLayout_10 = QtGui.QHBoxLayout()
        self.horizontalLayout_10.setSpacing(0)
        self.horizontalLayout_10.setObjectName(_fromUtf8("horizontalLayout_10"))
        self.authorityLabel = QtGui.QLabel(self.LsgRecordGroupBox)
        self.authorityLabel.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.authorityLabel.setObjectName(_fromUtf8("authorityLabel"))
        self.horizontalLayout_10.addWidget(self.authorityLabel)
        self.authorityStackedWidget = QtGui.QStackedWidget(self.LsgRecordGroupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.authorityStackedWidget.sizePolicy().hasHeightForWidth())
        self.authorityStackedWidget.setSizePolicy(sizePolicy)
        self.authorityStackedWidget.setMinimumSize(QtCore.QSize(290, 20))
        self.authorityStackedWidget.setObjectName(_fromUtf8("authorityStackedWidget"))
        self.authorityReadOnlyPage = QtGui.QWidget()
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.authorityReadOnlyPage.sizePolicy().hasHeightForWidth())
        self.authorityReadOnlyPage.setSizePolicy(sizePolicy)
        self.authorityReadOnlyPage.setMinimumSize(QtCore.QSize(290, 20))
        self.authorityReadOnlyPage.setObjectName(_fromUtf8("authorityReadOnlyPage"))
        self.gridLayout_19 = QtGui.QGridLayout(self.authorityReadOnlyPage)
        self.gridLayout_19.setSpacing(0)
        self.gridLayout_19.setContentsMargins(12, 0, 0, 0)
        self.gridLayout_19.setObjectName(_fromUtf8("gridLayout_19"))
        self.authorityLineEdit = QtGui.QLineEdit(self.authorityReadOnlyPage)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.authorityLineEdit.sizePolicy().hasHeightForWidth())
        self.authorityLineEdit.setSizePolicy(sizePolicy)
        self.authorityLineEdit.setMinimumSize(QtCore.QSize(278, 20))
        self.authorityLineEdit.setMaximumSize(QtCore.QSize(16777215, 20))
        self.authorityLineEdit.setStyleSheet(_fromUtf8("border-width:0.5px;\n"
"border-style: solid;\n"
"border-radius: 2px;\n"
"border-color:  rgb(100,100,100);\n"
"background-color: rgb(213, 234, 234);"))
        self.authorityLineEdit.setInputMask(_fromUtf8(""))
        self.authorityLineEdit.setReadOnly(True)
        self.authorityLineEdit.setObjectName(_fromUtf8("authorityLineEdit"))
        self.gridLayout_19.addWidget(self.authorityLineEdit, 0, 1, 1, 1)
        spacerItem17 = QtGui.QSpacerItem(6, 20, QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Minimum)
        self.gridLayout_19.addItem(spacerItem17, 0, 0, 1, 1)
        self.authorityStackedWidget.addWidget(self.authorityReadOnlyPage)
        self.authorityModifyPage = QtGui.QWidget()
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.authorityModifyPage.sizePolicy().hasHeightForWidth())
        self.authorityModifyPage.setSizePolicy(sizePolicy)
        self.authorityModifyPage.setMinimumSize(QtCore.QSize(290, 20))
        self.authorityModifyPage.setObjectName(_fromUtf8("authorityModifyPage"))
        self.gridLayout_21 = QtGui.QGridLayout(self.authorityModifyPage)
        self.gridLayout_21.setSpacing(0)
        self.gridLayout_21.setContentsMargins(12, 0, 0, 0)
        self.gridLayout_21.setObjectName(_fromUtf8("gridLayout_21"))
        self.authorityComboBox = QtGui.QComboBox(self.authorityModifyPage)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.authorityComboBox.sizePolicy().hasHeightForWidth())
        self.authorityComboBox.setSizePolicy(sizePolicy)
        self.authorityComboBox.setMinimumSize(QtCore.QSize(278, 20))
        self.authorityComboBox.setMaximumSize(QtCore.QSize(16777215, 20))
        self.authorityComboBox.setObjectName(_fromUtf8("authorityComboBox"))
        self.gridLayout_21.addWidget(self.authorityComboBox, 0, 1, 1, 1)
        spacerItem18 = QtGui.QSpacerItem(6, 20, QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Minimum)
        self.gridLayout_21.addItem(spacerItem18, 0, 0, 1, 1)
        self.authorityStackedWidget.addWidget(self.authorityModifyPage)
        self.horizontalLayout_10.addWidget(self.authorityStackedWidget)
        self.gridLayout_28.addLayout(self.horizontalLayout_10, 6, 0, 1, 1)
        self.gridLayout_12.addWidget(self.LsgRecordGroupBox, 0, 0, 2, 1)
        self.otherGroupBox = QtGui.QGroupBox(self.groupBox_3)
        self.otherGroupBox.setMinimumSize(QtCore.QSize(550, 85))
        self.otherGroupBox.setMaximumSize(QtCore.QSize(16777215, 85))
        self.otherGroupBox.setObjectName(_fromUtf8("otherGroupBox"))
        self.gridLayout_23 = QtGui.QGridLayout(self.otherGroupBox)
        self.gridLayout_23.setObjectName(_fromUtf8("gridLayout_23"))
        self.horizontalLayout_13 = QtGui.QHBoxLayout()
        self.horizontalLayout_13.setObjectName(_fromUtf8("horizontalLayout_13"))
        self.label_2 = QtGui.QLabel(self.otherGroupBox)
        self.label_2.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.horizontalLayout_13.addWidget(self.label_2)
        self.stateStackedWidget = QtGui.QStackedWidget(self.otherGroupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.stateStackedWidget.sizePolicy().hasHeightForWidth())
        self.stateStackedWidget.setSizePolicy(sizePolicy)
        self.stateStackedWidget.setMinimumSize(QtCore.QSize(200, 20))
        self.stateStackedWidget.setMaximumSize(QtCore.QSize(200, 20))
        self.stateStackedWidget.setObjectName(_fromUtf8("stateStackedWidget"))
        self.stateReadOnlyPage = QtGui.QWidget()
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.stateReadOnlyPage.sizePolicy().hasHeightForWidth())
        self.stateReadOnlyPage.setSizePolicy(sizePolicy)
        self.stateReadOnlyPage.setMinimumSize(QtCore.QSize(200, 20))
        self.stateReadOnlyPage.setMaximumSize(QtCore.QSize(16777215, 20))
        self.stateReadOnlyPage.setObjectName(_fromUtf8("stateReadOnlyPage"))
        self.stateLineEdit = QtGui.QLineEdit(self.stateReadOnlyPage)
        self.stateLineEdit.setGeometry(QtCore.QRect(0, 0, 200, 20))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.stateLineEdit.sizePolicy().hasHeightForWidth())
        self.stateLineEdit.setSizePolicy(sizePolicy)
        self.stateLineEdit.setMinimumSize(QtCore.QSize(200, 0))
        self.stateLineEdit.setMaximumSize(QtCore.QSize(16777215, 20))
        self.stateLineEdit.setStyleSheet(_fromUtf8("border-width:0.5px;\n"
"border-style: solid;\n"
"border-radius: 2px;\n"
"border-color:  rgb(100,100,100);\n"
"background-color: rgb(213, 234, 234);"))
        self.stateLineEdit.setReadOnly(True)
        self.stateLineEdit.setObjectName(_fromUtf8("stateLineEdit"))
        self.stateStackedWidget.addWidget(self.stateReadOnlyPage)
        self.stateModifyPage = QtGui.QWidget()
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.stateModifyPage.sizePolicy().hasHeightForWidth())
        self.stateModifyPage.setSizePolicy(sizePolicy)
        self.stateModifyPage.setObjectName(_fromUtf8("stateModifyPage"))
        self.stateComboBox = QtGui.QComboBox(self.stateModifyPage)
        self.stateComboBox.setGeometry(QtCore.QRect(0, 0, 200, 20))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.stateComboBox.sizePolicy().hasHeightForWidth())
        self.stateComboBox.setSizePolicy(sizePolicy)
        self.stateComboBox.setMinimumSize(QtCore.QSize(200, 0))
        self.stateComboBox.setMaximumSize(QtCore.QSize(16777215, 41))
        self.stateComboBox.setObjectName(_fromUtf8("stateComboBox"))
        self.stateStackedWidget.addWidget(self.stateModifyPage)
        self.horizontalLayout_13.addWidget(self.stateStackedWidget)
        spacerItem19 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_13.addItem(spacerItem19)
        self.label_3 = QtGui.QLabel(self.otherGroupBox)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.horizontalLayout_13.addWidget(self.label_3)
        self.stateDateLineEdit = QtGui.QLineEdit(self.otherGroupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.stateDateLineEdit.sizePolicy().hasHeightForWidth())
        self.stateDateLineEdit.setSizePolicy(sizePolicy)
        self.stateDateLineEdit.setMinimumSize(QtCore.QSize(0, 20))
        self.stateDateLineEdit.setMaximumSize(QtCore.QSize(80, 20))
        self.stateDateLineEdit.setStyleSheet(_fromUtf8("border-width:0.5px;\n"
"border-style: solid;\n"
"border-radius: 2px;\n"
"border-color:  rgb(100,100,100);\n"
"background-color: rgb(213, 234, 234);"))
        self.stateDateLineEdit.setReadOnly(True)
        self.stateDateLineEdit.setObjectName(_fromUtf8("stateDateLineEdit"))
        self.horizontalLayout_13.addWidget(self.stateDateLineEdit)
        self.gridLayout_23.addLayout(self.horizontalLayout_13, 0, 0, 1, 1)
        self.horizontalLayout_14 = QtGui.QHBoxLayout()
        self.horizontalLayout_14.setContentsMargins(-1, -1, 10, -1)
        self.horizontalLayout_14.setObjectName(_fromUtf8("horizontalLayout_14"))
        self.classLabel = QtGui.QLabel(self.otherGroupBox)
        self.classLabel.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.classLabel.setObjectName(_fromUtf8("classLabel"))
        self.horizontalLayout_14.addWidget(self.classLabel)
        self.classStackedWidget = QtGui.QStackedWidget(self.otherGroupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.classStackedWidget.sizePolicy().hasHeightForWidth())
        self.classStackedWidget.setSizePolicy(sizePolicy)
        self.classStackedWidget.setMinimumSize(QtCore.QSize(0, 20))
        self.classStackedWidget.setMaximumSize(QtCore.QSize(200, 20))
        self.classStackedWidget.setSizeIncrement(QtCore.QSize(0, 0))
        self.classStackedWidget.setObjectName(_fromUtf8("classStackedWidget"))
        self.classReadOnlyPage = QtGui.QWidget()
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.classReadOnlyPage.sizePolicy().hasHeightForWidth())
        self.classReadOnlyPage.setSizePolicy(sizePolicy)
        self.classReadOnlyPage.setMinimumSize(QtCore.QSize(200, 20))
        self.classReadOnlyPage.setMaximumSize(QtCore.QSize(200, 20))
        self.classReadOnlyPage.setObjectName(_fromUtf8("classReadOnlyPage"))
        self.gridLayout_29 = QtGui.QGridLayout(self.classReadOnlyPage)
        self.gridLayout_29.setSpacing(0)
        self.gridLayout_29.setMargin(0)
        self.gridLayout_29.setObjectName(_fromUtf8("gridLayout_29"))
        self.classLineEdit = QtGui.QLineEdit(self.classReadOnlyPage)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.classLineEdit.sizePolicy().hasHeightForWidth())
        self.classLineEdit.setSizePolicy(sizePolicy)
        self.classLineEdit.setMinimumSize(QtCore.QSize(200, 20))
        self.classLineEdit.setMaximumSize(QtCore.QSize(16777215, 20))
        self.classLineEdit.setStyleSheet(_fromUtf8("border-width:0.5px;\n"
"border-style: solid;\n"
"border-radius: 2px;\n"
"border-color:  rgb(100,100,100);\n"
"background-color: rgb(213, 234, 234);"))
        self.classLineEdit.setReadOnly(True)
        self.classLineEdit.setObjectName(_fromUtf8("classLineEdit"))
        self.gridLayout_29.addWidget(self.classLineEdit, 0, 0, 1, 1)
        self.classStackedWidget.addWidget(self.classReadOnlyPage)
        self.classModifyPage = QtGui.QWidget()
        self.classModifyPage.setObjectName(_fromUtf8("classModifyPage"))
        self.gridLayout_22 = QtGui.QGridLayout(self.classModifyPage)
        self.gridLayout_22.setSpacing(0)
        self.gridLayout_22.setMargin(0)
        self.gridLayout_22.setObjectName(_fromUtf8("gridLayout_22"))
        self.classComboBox = QtGui.QComboBox(self.classModifyPage)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.classComboBox.sizePolicy().hasHeightForWidth())
        self.classComboBox.setSizePolicy(sizePolicy)
        self.classComboBox.setMinimumSize(QtCore.QSize(0, 20))
        self.classComboBox.setMaximumSize(QtCore.QSize(200, 20))
        self.classComboBox.setObjectName(_fromUtf8("classComboBox"))
        self.gridLayout_22.addWidget(self.classComboBox, 0, 0, 1, 1)
        self.classStackedWidget.addWidget(self.classModifyPage)
        self.horizontalLayout_14.addWidget(self.classStackedWidget)
        spacerItem20 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_14.addItem(spacerItem20)
        self.gridLayout_23.addLayout(self.horizontalLayout_14, 1, 0, 1, 1)
        self.gridLayout_12.addWidget(self.otherGroupBox, 3, 0, 1, 1)
        self.linkEsuGroupBox = QtGui.QGroupBox(self.groupBox_3)
        self.linkEsuGroupBox.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.linkEsuGroupBox.setObjectName(_fromUtf8("linkEsuGroupBox"))
        self.gridLayout_20 = QtGui.QGridLayout(self.linkEsuGroupBox)
        self.gridLayout_20.setObjectName(_fromUtf8("gridLayout_20"))
        self.linkEsuListWidget = QtGui.QListWidget(self.linkEsuGroupBox)
        self.linkEsuListWidget.setMinimumSize(QtCore.QSize(0, 0))
        self.linkEsuListWidget.setStyleSheet(_fromUtf8("border-width:0.5px;\n"
"border-style: solid;\n"
"border-radius: 2px;\n"
"border-color:  rgb(100,100,100);\n"
"background-color: rgb(213, 234, 234);"))
        self.linkEsuListWidget.setObjectName(_fromUtf8("linkEsuListWidget"))
        self.gridLayout_20.addWidget(self.linkEsuListWidget, 0, 0, 1, 1)
        self.editEsuPushButton = QtGui.QPushButton(self.linkEsuGroupBox)
        self.editEsuPushButton.setEnabled(False)
        self.editEsuPushButton.setMinimumSize(QtCore.QSize(0, 33))
        self.editEsuPushButton.setMaximumSize(QtCore.QSize(153, 23))
        self.editEsuPushButton.setObjectName(_fromUtf8("editEsuPushButton"))
        self.gridLayout_20.addWidget(self.editEsuPushButton, 0, 1, 1, 1)
        self.gridLayout_12.addWidget(self.linkEsuGroupBox, 2, 1, 2, 1)
        self.groupBox = QtGui.QGroupBox(self.groupBox_3)
        self.groupBox.setMinimumSize(QtCore.QSize(421, 115))
        self.groupBox.setMaximumSize(QtCore.QSize(16777215, 125))
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self.gridLayout_24 = QtGui.QGridLayout(self.groupBox)
        self.gridLayout_24.setObjectName(_fromUtf8("gridLayout_24"))
        self.gridLayout_15 = QtGui.QGridLayout()
        self.gridLayout_15.setObjectName(_fromUtf8("gridLayout_15"))
        self.endYLabel = QtGui.QLabel(self.groupBox)
        self.endYLabel.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.endYLabel.setAutoFillBackground(False)
        self.endYLabel.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.endYLabel.setObjectName(_fromUtf8("endYLabel"))
        self.gridLayout_15.addWidget(self.endYLabel, 1, 2, 1, 1)
        self.endXLineEdit = QtGui.QLineEdit(self.groupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.endXLineEdit.sizePolicy().hasHeightForWidth())
        self.endXLineEdit.setSizePolicy(sizePolicy)
        self.endXLineEdit.setMinimumSize(QtCore.QSize(106, 20))
        self.endXLineEdit.setMaximumSize(QtCore.QSize(16777215, 20))
        self.endXLineEdit.setStyleSheet(_fromUtf8("border-width:0.5px;\n"
"border-style: solid;\n"
"border-radius: 2px;\n"
"border-color:  rgb(100,100,100);\n"
"background-color: rgb(213, 234, 234);"))
        self.endXLineEdit.setReadOnly(True)
        self.endXLineEdit.setObjectName(_fromUtf8("endXLineEdit"))
        self.gridLayout_15.addWidget(self.endXLineEdit, 1, 1, 1, 1)
        self.endXLabel = QtGui.QLabel(self.groupBox)
        self.endXLabel.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.endXLabel.setObjectName(_fromUtf8("endXLabel"))
        self.gridLayout_15.addWidget(self.endXLabel, 1, 0, 1, 1)
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        spacerItem21 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem21)
        self.tolLabel = QtGui.QLabel(self.groupBox)
        self.tolLabel.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.tolLabel.setObjectName(_fromUtf8("tolLabel"))
        self.horizontalLayout_3.addWidget(self.tolLabel)
        self.tolLineEdit = QtGui.QLineEdit(self.groupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tolLineEdit.sizePolicy().hasHeightForWidth())
        self.tolLineEdit.setSizePolicy(sizePolicy)
        self.tolLineEdit.setMinimumSize(QtCore.QSize(50, 0))
        self.tolLineEdit.setMaximumSize(QtCore.QSize(50, 20))
        self.tolLineEdit.setStyleSheet(_fromUtf8("border-width:0.5px;\n"
"border-style: solid;\n"
"border-radius: 2px;\n"
"border-color:  rgb(100,100,100);\n"
"background-color: rgb(213, 234, 234);"))
        self.tolLineEdit.setReadOnly(True)
        self.tolLineEdit.setObjectName(_fromUtf8("tolLineEdit"))
        self.horizontalLayout_3.addWidget(self.tolLineEdit)
        self.label = QtGui.QLabel(self.groupBox)
        self.label.setMaximumSize(QtCore.QSize(10, 16777215))
        self.label.setObjectName(_fromUtf8("label"))
        self.horizontalLayout_3.addWidget(self.label)
        self.gridLayout_15.addLayout(self.horizontalLayout_3, 0, 4, 1, 1)
        self.startYLabel = QtGui.QLabel(self.groupBox)
        self.startYLabel.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.startYLabel.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.startYLabel.setObjectName(_fromUtf8("startYLabel"))
        self.gridLayout_15.addWidget(self.startYLabel, 0, 2, 1, 1)
        self.startYLineEdit = QtGui.QLineEdit(self.groupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.startYLineEdit.sizePolicy().hasHeightForWidth())
        self.startYLineEdit.setSizePolicy(sizePolicy)
        self.startYLineEdit.setMinimumSize(QtCore.QSize(84, 20))
        self.startYLineEdit.setMaximumSize(QtCore.QSize(16777215, 20))
        self.startYLineEdit.setStyleSheet(_fromUtf8("border-width:0.5px;\n"
"border-style: solid;\n"
"border-radius: 2px;\n"
"border-color:  rgb(100,100,100);\n"
"background-color: rgb(213, 234, 234);"))
        self.startYLineEdit.setReadOnly(True)
        self.startYLineEdit.setObjectName(_fromUtf8("startYLineEdit"))
        self.gridLayout_15.addWidget(self.startYLineEdit, 0, 3, 1, 1)
        self.startXLineEdit = QtGui.QLineEdit(self.groupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.startXLineEdit.sizePolicy().hasHeightForWidth())
        self.startXLineEdit.setSizePolicy(sizePolicy)
        self.startXLineEdit.setMinimumSize(QtCore.QSize(84, 20))
        self.startXLineEdit.setMaximumSize(QtCore.QSize(16777215, 20))
        self.startXLineEdit.setStyleSheet(_fromUtf8("border-width:0.5px;\n"
"border-style: solid;\n"
"border-radius: 2px;\n"
"border-color:  rgb(100,100,100);\n"
"background-color: rgb(213, 234, 234);"))
        self.startXLineEdit.setReadOnly(True)
        self.startXLineEdit.setObjectName(_fromUtf8("startXLineEdit"))
        self.gridLayout_15.addWidget(self.startXLineEdit, 0, 1, 1, 1)
        self.startXLabel = QtGui.QLabel(self.groupBox)
        self.startXLabel.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.startXLabel.setObjectName(_fromUtf8("startXLabel"))
        self.gridLayout_15.addWidget(self.startXLabel, 0, 0, 1, 1)
        self.horizontalLayout_11 = QtGui.QHBoxLayout()
        self.horizontalLayout_11.setObjectName(_fromUtf8("horizontalLayout_11"))
        spacerItem22 = QtGui.QSpacerItem(20, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_11.addItem(spacerItem22)
        self.showPushButton = QtGui.QPushButton(self.groupBox)
        self.showPushButton.setMaximumSize(QtCore.QSize(60, 25))
        self.showPushButton.setObjectName(_fromUtf8("showPushButton"))
        self.horizontalLayout_11.addWidget(self.showPushButton)
        spacerItem23 = QtGui.QSpacerItem(4, 20, QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_11.addItem(spacerItem23)
        self.gridLayout_15.addLayout(self.horizontalLayout_11, 1, 4, 1, 1)
        self.endYLineEdit = QtGui.QLineEdit(self.groupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.endYLineEdit.sizePolicy().hasHeightForWidth())
        self.endYLineEdit.setSizePolicy(sizePolicy)
        self.endYLineEdit.setMinimumSize(QtCore.QSize(106, 20))
        self.endYLineEdit.setMaximumSize(QtCore.QSize(16777215, 20))
        self.endYLineEdit.setStyleSheet(_fromUtf8("border-width:0.5px;\n"
"border-style: solid;\n"
"border-radius: 2px;\n"
"border-color:  rgb(100,100,100);\n"
"background-color: rgb(213, 234, 234);"))
        self.endYLineEdit.setReadOnly(True)
        self.endYLineEdit.setObjectName(_fromUtf8("endYLineEdit"))
        self.gridLayout_15.addWidget(self.endYLineEdit, 1, 3, 1, 1)
        self.gridLayout_24.addLayout(self.gridLayout_15, 0, 0, 1, 1)
        self.editCoordsPushButton = QtGui.QPushButton(self.groupBox)
        self.editCoordsPushButton.setEnabled(False)
        self.editCoordsPushButton.setMinimumSize(QtCore.QSize(0, 23))
        self.editCoordsPushButton.setMaximumSize(QtCore.QSize(153, 23))
        self.editCoordsPushButton.setObjectName(_fromUtf8("editCoordsPushButton"))
        self.gridLayout_24.addWidget(self.editCoordsPushButton, 1, 0, 1, 1)
        self.gridLayout_12.addWidget(self.groupBox, 2, 0, 1, 1)
        self.navigationGroupBox = QtGui.QGroupBox(self.groupBox_3)
        self.navigationGroupBox.setMinimumSize(QtCore.QSize(0, 0))
        self.navigationGroupBox.setMaximumSize(QtCore.QSize(16777215, 85))
        self.navigationGroupBox.setObjectName(_fromUtf8("navigationGroupBox"))
        self.gridLayout_7 = QtGui.QGridLayout(self.navigationGroupBox)
        self.gridLayout_7.setObjectName(_fromUtf8("gridLayout_7"))
        self.firstPushButton = QtGui.QPushButton(self.navigationGroupBox)
        self.firstPushButton.setMinimumSize(QtCore.QSize(0, 0))
        self.firstPushButton.setMaximumSize(QtCore.QSize(120, 16777215))
        self.firstPushButton.setObjectName(_fromUtf8("firstPushButton"))
        self.gridLayout_7.addWidget(self.firstPushButton, 0, 0, 1, 1)
        self.previousPushButton = QtGui.QPushButton(self.navigationGroupBox)
        self.previousPushButton.setMaximumSize(QtCore.QSize(120, 16777215))
        self.previousPushButton.setObjectName(_fromUtf8("previousPushButton"))
        self.gridLayout_7.addWidget(self.previousPushButton, 0, 1, 1, 1)
        self.nextPushButton = QtGui.QPushButton(self.navigationGroupBox)
        self.nextPushButton.setMaximumSize(QtCore.QSize(120, 16777215))
        self.nextPushButton.setObjectName(_fromUtf8("nextPushButton"))
        self.gridLayout_7.addWidget(self.nextPushButton, 0, 2, 1, 1)
        self.lastPushButton = QtGui.QPushButton(self.navigationGroupBox)
        self.lastPushButton.setMaximumSize(QtCore.QSize(120, 16777215))
        self.lastPushButton.setObjectName(_fromUtf8("lastPushButton"))
        self.gridLayout_7.addWidget(self.lastPushButton, 0, 3, 1, 1)
        self.gridLayout_12.addWidget(self.navigationGroupBox, 5, 0, 1, 1)
        self.crossReferenceGroupBox = QtGui.QGroupBox(self.groupBox_3)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.crossReferenceGroupBox.sizePolicy().hasHeightForWidth())
        self.crossReferenceGroupBox.setSizePolicy(sizePolicy)
        self.crossReferenceGroupBox.setMinimumSize(QtCore.QSize(378, 230))
        self.crossReferenceGroupBox.setMaximumSize(QtCore.QSize(16777215, 250))
        self.crossReferenceGroupBox.setBaseSize(QtCore.QSize(0, 25))
        self.crossReferenceGroupBox.setObjectName(_fromUtf8("crossReferenceGroupBox"))
        self.gridLayout_2 = QtGui.QGridLayout(self.crossReferenceGroupBox)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.crossReferenceTableView = QtGui.QTableView(self.crossReferenceGroupBox)
        self.crossReferenceTableView.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("MS Shell Dlg 2"))
        font.setPointSize(8)
        self.crossReferenceTableView.setFont(font)
        self.crossReferenceTableView.setStyleSheet(_fromUtf8("border-width:0.5px;\n"
"border-style: solid;\n"
"border-radius: 2px;\n"
"border-color:  rgb(100,100,100);\n"
"background-color: rgb(213, 234, 234);"))
        self.crossReferenceTableView.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.crossReferenceTableView.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.crossReferenceTableView.setEditTriggers(QtGui.QAbstractItemView.AllEditTriggers)
        self.crossReferenceTableView.setSelectionMode(QtGui.QAbstractItemView.SingleSelection)
        self.crossReferenceTableView.setGridStyle(QtCore.Qt.NoPen)
        self.crossReferenceTableView.setObjectName(_fromUtf8("crossReferenceTableView"))
        self.crossReferenceTableView.horizontalHeader().setVisible(False)
        self.crossReferenceTableView.horizontalHeader().setStretchLastSection(True)
        self.crossReferenceTableView.verticalHeader().setVisible(False)
        self.gridLayout_2.addWidget(self.crossReferenceTableView, 1, 0, 1, 1)
        self.viewPushButton = QtGui.QPushButton(self.crossReferenceGroupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.viewPushButton.sizePolicy().hasHeightForWidth())
        self.viewPushButton.setSizePolicy(sizePolicy)
        self.viewPushButton.setMinimumSize(QtCore.QSize(75, 0))
        self.viewPushButton.setMaximumSize(QtCore.QSize(60, 16777215))
        self.viewPushButton.setObjectName(_fromUtf8("viewPushButton"))
        self.gridLayout_2.addWidget(self.viewPushButton, 1, 1, 1, 1)
        self.gridLayout_12.addWidget(self.crossReferenceGroupBox, 1, 1, 1, 1)
        spacerItem24 = QtGui.QSpacerItem(20, 5, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout_12.addItem(spacerItem24, 4, 0, 1, 1)
        self.gridLayout_34.addWidget(self.groupBox_3, 0, 0, 1, 1)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.gridLayout_32.addWidget(self.scrollArea, 0, 0, 1, 1)

        self.retranslateUi(streetBrowserDialog)
        self.srwrTabWidget.setCurrentIndex(0)
        self.localityStackedWidget.setCurrentIndex(0)
        self.townStackedWidget.setCurrentIndex(0)
        self.typeStackedWidget.setCurrentIndex(0)
        self.startDateStackedWidget.setCurrentIndex(0)
        self.countyStackedWidget.setCurrentIndex(0)
        self.authorityStackedWidget.setCurrentIndex(0)
        self.stateStackedWidget.setCurrentIndex(0)
        self.classStackedWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(streetBrowserDialog)

    def retranslateUi(self, streetBrowserDialog):
        streetBrowserDialog.setWindowTitle(_translate("streetBrowserDialog", "roadNet - Street Browser", None))
        self.srwrRecordsGroupBox.setTitle(_translate("streetBrowserDialog", "SRWR Records", None))
        self.srwrTabWidget.setTabText(self.srwrTabWidget.indexOf(self.maintenanceTab), _translate("streetBrowserDialog", "Maintenance", None))
        self.srwrTabWidget.setTabText(self.srwrTabWidget.indexOf(self.specialDesignationsTab), _translate("streetBrowserDialog", "Special Designations", None))
        self.srwrTabWidget.setTabText(self.srwrTabWidget.indexOf(self.reinstatementCatsTab), _translate("streetBrowserDialog", "Reinstatement Categories", None))
        self.groupBox_2.setTitle(_translate("streetBrowserDialog", "Maintenance Operations", None))
        self.srwrAddPushButton.setText(_translate("streetBrowserDialog", "Add", None))
        self.srwrModifyPushButton.setText(_translate("streetBrowserDialog", "Modify", None))
        self.srwrDeletePushButton.setText(_translate("streetBrowserDialog", "Delete", None))
        self.srwrViewPushButton.setText(_translate("streetBrowserDialog", "View", None))
        self.srwrExtentPushButton.setText(_translate("streetBrowserDialog", "Show Extents", None))
        self.groupBox_3.setTitle(_translate("streetBrowserDialog", "LSG Record", None))
        self.srwrPushButton.setText(_translate("streetBrowserDialog", "Show SRWR Details", None))
        self.operationsGroupBox.setTitle(_translate("streetBrowserDialog", "LSG Operations", None))
        self.addPushButton.setText(_translate("streetBrowserDialog", "Add", None))
        self.modifyPushButton.setText(_translate("streetBrowserDialog", "Modify", None))
        self.closeOpPushButton.setText(_translate("streetBrowserDialog", "Delete", None))
        self.filterPushButton.setText(_translate("streetBrowserDialog", "Filter", None))
        self.mapPushButton.setText(_translate("streetBrowserDialog", "Map", None))
        self.LsgRecordGroupBox.setTitle(_translate("streetBrowserDialog", "Record", None))
        self.descriptionLabel.setText(_translate("streetBrowserDialog", "Description", None))
        self.localityLabel.setText(_translate("streetBrowserDialog", "Locality", None))
        self.townLabel.setText(_translate("streetBrowserDialog", "Town", None))
        self.typeLabel.setText(_translate("streetBrowserDialog", "Type", None))
        self.startDateLabel.setText(_translate("streetBrowserDialog", "Start Date", None))
        self.entryDateLabel.setText(_translate("streetBrowserDialog", "Entry Date", None))
        self.lastUpdateLabel.setText(_translate("streetBrowserDialog", "Last Update", None))
        self.byLabel.setText(_translate("streetBrowserDialog", "By", None))
        self.countyLabel.setText(_translate("streetBrowserDialog", "County", None))
        self.usrnLabel_2.setText(_translate("streetBrowserDialog", "USRN", None))
        self.versionLabel.setText(_translate("streetBrowserDialog", "Version", None))
        self.authorityLabel.setText(_translate("streetBrowserDialog", "Authority", None))
        self.otherGroupBox.setTitle(_translate("streetBrowserDialog", "Other", None))
        self.label_2.setText(_translate("streetBrowserDialog", "State", None))
        self.label_3.setText(_translate("streetBrowserDialog", "Date:", None))
        self.classLabel.setText(_translate("streetBrowserDialog", "Class", None))
        self.linkEsuGroupBox.setTitle(_translate("streetBrowserDialog", "ESUs", None))
        self.editEsuPushButton.setText(_translate("streetBrowserDialog", "Edit ESU\n"
"Links", None))
        self.groupBox.setTitle(_translate("streetBrowserDialog", "Coordinates", None))
        self.endYLabel.setText(_translate("streetBrowserDialog", "End Y", None))
        self.endXLabel.setText(_translate("streetBrowserDialog", "End X", None))
        self.tolLabel.setText(_translate("streetBrowserDialog", "Tol", None))
        self.label.setText(_translate("streetBrowserDialog", "m", None))
        self.startYLabel.setText(_translate("streetBrowserDialog", "Start Y", None))
        self.startXLabel.setText(_translate("streetBrowserDialog", "Start X", None))
        self.showPushButton.setText(_translate("streetBrowserDialog", "Show", None))
        self.editCoordsPushButton.setText(_translate("streetBrowserDialog", "Edit Start/End Coordinates", None))
        self.navigationGroupBox.setTitle(_translate("streetBrowserDialog", "Navigation", None))
        self.firstPushButton.setText(_translate("streetBrowserDialog", "First", None))
        self.previousPushButton.setText(_translate("streetBrowserDialog", "Previous", None))
        self.nextPushButton.setText(_translate("streetBrowserDialog", "Next", None))
        self.lastPushButton.setText(_translate("streetBrowserDialog", "Last", None))
        self.crossReferenceGroupBox.setTitle(_translate("streetBrowserDialog", "Cross Reference", None))
        self.viewPushButton.setText(_translate("streetBrowserDialog", "View", None))


if __name__ == "__main__":
    import sys
    app = QtGui.QApplication(sys.argv)
    streetBrowserDialog = QtGui.QDialog()
    ui = Ui_streetBrowserDialog()
    ui.setupUi(streetBrowserDialog)
    streetBrowserDialog.show()
    sys.exit(app.exec_())

